# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding/embed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding/embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65mbedding/embed.proto\x12\x1blightrag.eventbus.topics.v1\"%\n\x0f\x45mbeddingVector\x12\x12\n\x06values\x18\x01 \x03(\x02\x42\x02\x10\x01\"\x1f\n\x0e\x45mbeddingInput\x12\r\n\x05texts\x18\x01 \x03(\t\"S\n\x0f\x45mbeddingOutput\x12@\n\nembeddings\x18\x01 \x03(\x0b\x32,.lightrag.eventbus.topics.v1.EmbeddingVectorBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding.embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topics'
  _globals['_EMBEDDINGVECTOR'].fields_by_name['values']._loaded_options = None
  _globals['_EMBEDDINGVECTOR'].fields_by_name['values']._serialized_options = b'\020\001'
  _globals['_EMBEDDINGVECTOR']._serialized_start=54
  _globals['_EMBEDDINGVECTOR']._serialized_end=91
  _globals['_EMBEDDINGINPUT']._serialized_start=93
  _globals['_EMBEDDINGINPUT']._serialized_end=124
  _globals['_EMBEDDINGOUTPUT']._serialized_start=126
  _globals['_EMBEDDINGOUTPUT']._serialized_end=209
# @@protoc_insertion_point(module_scope)
