// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: llm/completion.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lightrag.eventbus.topics.v1";

export interface CompleteInput {
  /** 主提示词（user role 内容） */
  prompt: string;
  /** 系统提示词（可选，空字符串=无） */
  systemPrompt: string;
  /** 对话历史（可选，gleaning / 多轮场景） */
  historyMessages: ChatMessage[];
  /** 是否启用 Chain-of-Thought（默认 false） */
  enableCot: boolean;
  /** 是否流式输出（默认 false） */
  stream: boolean;
  /** 优先级：5=查询, 8=摘要, 10=索引（默认 10） */
  priority: number;
  /** 缓存类型标识（如 "extract", "summary", "keywords"） */
  cacheType: string;
  /** 关联的 chunk ID（用于缓存 key 生成，可选） */
  chunkId: string;
  /** 额外参数（如 keyword_extraction=true） */
  extraKwargs: { [key: string]: string };
}

export interface CompleteInput_ExtraKwargsEntry {
  key: string;
  value: string;
}

export interface ChatMessage {
  /** "user" 或 "assistant" */
  role: string;
  /** 消息内容 */
  content: string;
}

export interface CompleteOutput {
  /** 生成的文本响应（非流式） */
  response: string;
  /** 响应 token 数（可选，用于监控） */
  tokenCount: number;
  /** 实际使用的模型名（可选） */
  model: string;
}

function createBaseCompleteInput(): CompleteInput {
  return {
    prompt: "",
    systemPrompt: "",
    historyMessages: [],
    enableCot: false,
    stream: false,
    priority: 0,
    cacheType: "",
    chunkId: "",
    extraKwargs: {},
  };
}

export const CompleteInput: MessageFns<CompleteInput> = {
  encode(message: CompleteInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.prompt !== "") {
      writer.uint32(10).string(message.prompt);
    }
    if (message.systemPrompt !== "") {
      writer.uint32(18).string(message.systemPrompt);
    }
    for (const v of message.historyMessages) {
      ChatMessage.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.enableCot !== false) {
      writer.uint32(32).bool(message.enableCot);
    }
    if (message.stream !== false) {
      writer.uint32(40).bool(message.stream);
    }
    if (message.priority !== 0) {
      writer.uint32(48).int32(message.priority);
    }
    if (message.cacheType !== "") {
      writer.uint32(58).string(message.cacheType);
    }
    if (message.chunkId !== "") {
      writer.uint32(66).string(message.chunkId);
    }
    globalThis.Object.entries(message.extraKwargs).forEach(([key, value]: [string, string]) => {
      CompleteInput_ExtraKwargsEntry.encode({ key: key as any, value }, writer.uint32(74).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.prompt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.historyMessages.push(ChatMessage.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.enableCot = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.stream = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.priority = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.cacheType = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.chunkId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          const entry9 = CompleteInput_ExtraKwargsEntry.decode(reader, reader.uint32());
          if (entry9.value !== undefined) {
            message.extraKwargs[entry9.key] = entry9.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CompleteInput>, I>>(base?: I): CompleteInput {
    return CompleteInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteInput>, I>>(object: I): CompleteInput {
    const message = createBaseCompleteInput();
    message.prompt = object.prompt ?? "";
    message.systemPrompt = object.systemPrompt ?? "";
    message.historyMessages = object.historyMessages?.map((e) => ChatMessage.fromPartial(e)) || [];
    message.enableCot = object.enableCot ?? false;
    message.stream = object.stream ?? false;
    message.priority = object.priority ?? 0;
    message.cacheType = object.cacheType ?? "";
    message.chunkId = object.chunkId ?? "";
    message.extraKwargs = (globalThis.Object.entries(object.extraKwargs ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseCompleteInput_ExtraKwargsEntry(): CompleteInput_ExtraKwargsEntry {
  return { key: "", value: "" };
}

export const CompleteInput_ExtraKwargsEntry: MessageFns<CompleteInput_ExtraKwargsEntry> = {
  encode(message: CompleteInput_ExtraKwargsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteInput_ExtraKwargsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteInput_ExtraKwargsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CompleteInput_ExtraKwargsEntry>, I>>(base?: I): CompleteInput_ExtraKwargsEntry {
    return CompleteInput_ExtraKwargsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteInput_ExtraKwargsEntry>, I>>(
    object: I,
  ): CompleteInput_ExtraKwargsEntry {
    const message = createBaseCompleteInput_ExtraKwargsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseChatMessage(): ChatMessage {
  return { role: "", content: "" };
}

export const ChatMessage: MessageFns<ChatMessage> = {
  encode(message: ChatMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.role !== "") {
      writer.uint32(10).string(message.role);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChatMessage>, I>>(base?: I): ChatMessage {
    return ChatMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatMessage>, I>>(object: I): ChatMessage {
    const message = createBaseChatMessage();
    message.role = object.role ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseCompleteOutput(): CompleteOutput {
  return { response: "", tokenCount: 0, model: "" };
}

export const CompleteOutput: MessageFns<CompleteOutput> = {
  encode(message: CompleteOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.response !== "") {
      writer.uint32(10).string(message.response);
    }
    if (message.tokenCount !== 0) {
      writer.uint32(16).int32(message.tokenCount);
    }
    if (message.model !== "") {
      writer.uint32(26).string(message.model);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.response = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tokenCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.model = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CompleteOutput>, I>>(base?: I): CompleteOutput {
    return CompleteOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteOutput>, I>>(object: I): CompleteOutput {
    const message = createBaseCompleteOutput();
    message.response = object.response ?? "";
    message.tokenCount = object.tokenCount ?? 0;
    message.model = object.model ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
