# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lightrag_eventbus_pb2 as lightrag__eventbus__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lightrag_eventbus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventBusStub(object):
    """==========================================
    3. gRPC 接口定义 (简化单向流架构)
    ==========================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSubscriber = channel.unary_unary(
                '/lightrag.eventbus.v1.EventBus/RegisterSubscriber',
                request_serializer=lightrag__eventbus__pb2.RegisterRequest.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/lightrag.eventbus.v1.EventBus/Subscribe',
                request_serializer=lightrag__eventbus__pb2.RegisterRequest.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.EventEnvelope.FromString,
                _registered_method=True)
        self.Respond = channel.unary_unary(
                '/lightrag.eventbus.v1.EventBus/Respond',
                request_serializer=lightrag__eventbus__pb2.SubscriberReply.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.PublishAndWait = channel.unary_unary(
                '/lightrag.eventbus.v1.EventBus/PublishAndWait',
                request_serializer=lightrag__eventbus__pb2.EventEnvelope.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.SubscriberReply.FromString,
                _registered_method=True)
        self.RegisterService = channel.unary_unary(
                '/lightrag.eventbus.v1.EventBus/RegisterService',
                request_serializer=lightrag__eventbus__pb2.RegisterServiceRequest.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.RegisterServiceResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/lightrag.eventbus.v1.EventBus/Heartbeat',
                request_serializer=lightrag__eventbus__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UnregisterService = channel.unary_unary(
                '/lightrag.eventbus.v1.EventBus/UnregisterService',
                request_serializer=lightrag__eventbus__pb2.UnregisterServiceRequest.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.ListServiceInstances = channel.unary_unary(
                '/lightrag.eventbus.v1.EventBus/ListServiceInstances',
                request_serializer=lightrag__eventbus__pb2.ListServiceInstancesRequest.SerializeToString,
                response_deserializer=lightrag__eventbus__pb2.ListServiceInstancesResponse.FromString,
                _registered_method=True)


class EventBusServicer(object):
    """==========================================
    3. gRPC 接口定义 (简化单向流架构)
    ==========================================

    """

    def RegisterSubscriber(self, request, context):
        """【控制平面】订阅者启动时注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """【数据平面】数据分发：订阅者只接收事件流 (单向流)
        稳定性更高，负载均衡更友好。订阅者需通过独立的 Respond RPC 传回结果。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Respond(self, request, context):
        """【数据平面】数据回传：订阅者处理完毕后通过独立的 RPC 返回结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishAndWait(self, request, context):
        """【数据平面】主服务(LightRAG)调用接口：发布事件并等待总线聚合结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterService(self, request, context):
        """【控制平面】服务实例注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """【控制平面】服务心跳续期
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterService(self, request, context):
        """【控制平面】服务实例注销
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceInstances(self, request, context):
        """【控制平面】查询服务实例列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventBusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSubscriber': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSubscriber,
                    request_deserializer=lightrag__eventbus__pb2.RegisterRequest.FromString,
                    response_serializer=lightrag__eventbus__pb2.RegisterResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=lightrag__eventbus__pb2.RegisterRequest.FromString,
                    response_serializer=lightrag__eventbus__pb2.EventEnvelope.SerializeToString,
            ),
            'Respond': grpc.unary_unary_rpc_method_handler(
                    servicer.Respond,
                    request_deserializer=lightrag__eventbus__pb2.SubscriberReply.FromString,
                    response_serializer=lightrag__eventbus__pb2.RegisterResponse.SerializeToString,
            ),
            'PublishAndWait': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishAndWait,
                    request_deserializer=lightrag__eventbus__pb2.EventEnvelope.FromString,
                    response_serializer=lightrag__eventbus__pb2.SubscriberReply.SerializeToString,
            ),
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=lightrag__eventbus__pb2.RegisterServiceRequest.FromString,
                    response_serializer=lightrag__eventbus__pb2.RegisterServiceResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=lightrag__eventbus__pb2.HeartbeatRequest.FromString,
                    response_serializer=lightrag__eventbus__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UnregisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterService,
                    request_deserializer=lightrag__eventbus__pb2.UnregisterServiceRequest.FromString,
                    response_serializer=lightrag__eventbus__pb2.RegisterResponse.SerializeToString,
            ),
            'ListServiceInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceInstances,
                    request_deserializer=lightrag__eventbus__pb2.ListServiceInstancesRequest.FromString,
                    response_serializer=lightrag__eventbus__pb2.ListServiceInstancesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lightrag.eventbus.v1.EventBus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lightrag.eventbus.v1.EventBus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventBus(object):
    """==========================================
    3. gRPC 接口定义 (简化单向流架构)
    ==========================================

    """

    @staticmethod
    def RegisterSubscriber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/RegisterSubscriber',
            lightrag__eventbus__pb2.RegisterRequest.SerializeToString,
            lightrag__eventbus__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/Subscribe',
            lightrag__eventbus__pb2.RegisterRequest.SerializeToString,
            lightrag__eventbus__pb2.EventEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Respond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/Respond',
            lightrag__eventbus__pb2.SubscriberReply.SerializeToString,
            lightrag__eventbus__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishAndWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/PublishAndWait',
            lightrag__eventbus__pb2.EventEnvelope.SerializeToString,
            lightrag__eventbus__pb2.SubscriberReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/RegisterService',
            lightrag__eventbus__pb2.RegisterServiceRequest.SerializeToString,
            lightrag__eventbus__pb2.RegisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/Heartbeat',
            lightrag__eventbus__pb2.HeartbeatRequest.SerializeToString,
            lightrag__eventbus__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/UnregisterService',
            lightrag__eventbus__pb2.UnregisterServiceRequest.SerializeToString,
            lightrag__eventbus__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lightrag.eventbus.v1.EventBus/ListServiceInstances',
            lightrag__eventbus__pb2.ListServiceInstancesRequest.SerializeToString,
            lightrag__eventbus__pb2.ListServiceInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
