# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: index/builder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'index/builder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from embedding import embed_pb2 as embedding_dot_embed__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13index/builder.proto\x12\x1blightrag.eventbus.topics.v1\x1a\x15\x65mbedding/embed.proto\"\xd4\x02\n\rIndexDocument\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x46\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x36.lightrag.eventbus.topics.v1.IndexDocument.FieldsEntry\x12H\n\x07vectors\x18\x04 \x03(\x0b\x32\x37.lightrag.eventbus.topics.v1.IndexDocument.VectorsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\\\n\x0cVectorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12;\n\x05value\x18\x02 \x01(\x0b\x32,.lightrag.eventbus.topics.v1.EmbeddingVector:\x02\x38\x01\"\x9c\x02\n\x0fIndexBuildInput\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12=\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32-.lightrag.eventbus.topics.v1.IndexBuildAction\x12=\n\tdocuments\x18\x03 \x03(\x0b\x32*.lightrag.eventbus.topics.v1.IndexDocument\x12H\n\x06\x63onfig\x18\x04 \x03(\x0b\x32\x38.lightrag.eventbus.topics.v1.IndexBuildInput.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x81\x01\n\x10IndexBuildOutput\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12\x15\n\rsuccess_count\x18\x02 \x01(\x05\x12\x14\n\x0c\x66\x61iled_count\x18\x03 \x01(\x05\x12\x1b\n\x13\x66\x61iled_document_ids\x18\x04 \x03(\t\x12\x0f\n\x07message\x18\x05 \x01(\t*\x94\x01\n\x10IndexBuildAction\x12\"\n\x1eINDEX_BUILD_ACTION_UNSPECIFIED\x10\x00\x12\x1d\n\x19INDEX_BUILD_ACTION_UPSERT\x10\x01\x12\x1d\n\x19INDEX_BUILD_ACTION_DELETE\x10\x02\x12\x1e\n\x1aINDEX_BUILD_ACTION_REBUILD\x10\x03\x42\x44ZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'index.builder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topics'
  _globals['_INDEXDOCUMENT_FIELDSENTRY']._loaded_options = None
  _globals['_INDEXDOCUMENT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_INDEXDOCUMENT_VECTORSENTRY']._loaded_options = None
  _globals['_INDEXDOCUMENT_VECTORSENTRY']._serialized_options = b'8\001'
  _globals['_INDEXBUILDINPUT_CONFIGENTRY']._loaded_options = None
  _globals['_INDEXBUILDINPUT_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_INDEXBUILDACTION']._serialized_start=838
  _globals['_INDEXBUILDACTION']._serialized_end=986
  _globals['_INDEXDOCUMENT']._serialized_start=76
  _globals['_INDEXDOCUMENT']._serialized_end=416
  _globals['_INDEXDOCUMENT_FIELDSENTRY']._serialized_start=277
  _globals['_INDEXDOCUMENT_FIELDSENTRY']._serialized_end=322
  _globals['_INDEXDOCUMENT_VECTORSENTRY']._serialized_start=324
  _globals['_INDEXDOCUMENT_VECTORSENTRY']._serialized_end=416
  _globals['_INDEXBUILDINPUT']._serialized_start=419
  _globals['_INDEXBUILDINPUT']._serialized_end=703
  _globals['_INDEXBUILDINPUT_CONFIGENTRY']._serialized_start=658
  _globals['_INDEXBUILDINPUT_CONFIGENTRY']._serialized_end=703
  _globals['_INDEXBUILDOUTPUT']._serialized_start=706
  _globals['_INDEXBUILDOUTPUT']._serialized_end=835
# @@protoc_insertion_point(module_scope)
