# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: index/retriever.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'index/retriever.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15index/retriever.proto\x12\x1blightrag.eventbus.topics.v1\"\xb3\x01\n\rRetrieveInput\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\x16\n\x0esemantic_ratio\x18\x04 \x01(\x02\x12\x18\n\x0cquery_vector\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x08\x65mbedder\x18\x06 \x01(\t\x12\x17\n\x0fscore_threshold\x18\x07 \x01(\x02\x12\x13\n\x0b\x66ilter_expr\x18\x08 \x01(\t\"\xbd\x01\n\x0eRetrieveResult\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12G\n\x06\x66ields\x18\x04 \x03(\x0b\x32\x37.lightrag.eventbus.topics.v1.RetrieveResult.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"v\n\x0eRetrieveOutput\x12<\n\x07results\x18\x01 \x03(\x0b\x32+.lightrag.eventbus.topics.v1.RetrieveResult\x12\x12\n\ntotal_hits\x18\x02 \x01(\x05\x12\x12\n\nindex_name\x18\x03 \x01(\tBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'index.retriever_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topics'
  _globals['_RETRIEVEINPUT'].fields_by_name['query_vector']._loaded_options = None
  _globals['_RETRIEVEINPUT'].fields_by_name['query_vector']._serialized_options = b'\020\001'
  _globals['_RETRIEVERESULT_FIELDSENTRY']._loaded_options = None
  _globals['_RETRIEVERESULT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_RETRIEVEINPUT']._serialized_start=55
  _globals['_RETRIEVEINPUT']._serialized_end=234
  _globals['_RETRIEVERESULT']._serialized_start=237
  _globals['_RETRIEVERESULT']._serialized_end=426
  _globals['_RETRIEVERESULT_FIELDSENTRY']._serialized_start=381
  _globals['_RETRIEVERESULT_FIELDSENTRY']._serialized_end=426
  _globals['_RETRIEVEOUTPUT']._serialized_start=428
  _globals['_RETRIEVEOUTPUT']._serialized_end=546
# @@protoc_insertion_point(module_scope)
