// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: rag/insert.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { EmbeddingVector } from "../index/builder";

export const protobufPackage = "lightrag.eventbus.topics.v1";

export interface ChunkingInput {
  /** 原始文档内容 */
  content: string;
  /** 序列化的 Tiktoken tokenizer */
  tokenizer: Uint8Array;
  /** chunk token 大小 (默认 1200) */
  chunkTokenSize: number;
  /** 重叠 token 数 (默认 100) */
  chunkOverlapTokenSize: number;
  /** 分隔符 */
  splitByCharacter: string;
  /** 仅按字符分割 (默认 false) */
  splitByCharacterOnly: boolean;
}

export interface ChunkingOutput {
  /** 分块结果列表 */
  chunks: ChunkItem[];
}

export interface ChunkItem {
  /** chunk 文本内容 */
  content: string;
  /** token 数量 */
  tokens: number;
  /** chunk 在文档中的序号 */
  chunkOrderIndex: number;
}

export interface EmbeddingInput {
  /** 待嵌入的文本列表 */
  texts: string[];
}

export interface EmbeddingOutput {
  /** 嵌入结果列表 (与输入 texts 顺序一一对应) */
  embeddings: EmbeddingVector[];
}

export interface OcrInput {
  /** 图片二进制数据 */
  image: Uint8Array;
  /** OCR 语言 (默认 auto) */
  language: string;
}

export interface OcrOutput {
  /** OCR 识别的文本 */
  text: string;
}

export interface LoadTextInput {
  /** 文件二进制内容 */
  fileContent: Uint8Array;
  /** 文件名（含扩展名） */
  fileName: string;
  /** 原始文件路径（可选） */
  filePath: string;
  /** 追踪 ID（可选） */
  trackId: string;
}

export interface LoadTextOutput {
  /** 提取的纯文本内容 */
  content: string;
  /** 回显文件名 */
  fileName: string;
  /** 回显文件路径 */
  filePath: string;
  /** 内容 MD5 hash（用于去重） */
  contentHash: string;
  /** 提取文本长度 */
  contentLength: number;
  /** 错误信息（空字符串=成功） */
  errorMessage: string;
}

export interface LoadPdfInput {
  /** PDF 文件二进制内容 */
  fileContent: Uint8Array;
  /** 文件名（含扩展名） */
  fileName: string;
  /** 原始文件路径（可选） */
  filePath: string;
  /** 追踪 ID（可选） */
  trackId: string;
  /** 加载引擎："native"（pypdf）/ "docling"（默认 "native"） */
  loadingEngine: string;
  /** PDF 解密密码（可选） */
  decryptPassword: string;
}

export interface LoadPdfOutput {
  /** 提取的纯文本内容 */
  content: string;
  /** 回显文件名 */
  fileName: string;
  /** 回显文件路径 */
  filePath: string;
  /** 内容 MD5 hash（用于去重） */
  contentHash: string;
  /** 提取文本长度 */
  contentLength: number;
  /** 错误信息（空字符串=成功） */
  errorMessage: string;
}

export interface LoadDocxInput {
  /** DOCX 文件二进制内容 */
  fileContent: Uint8Array;
  /** 文件名（含扩展名） */
  fileName: string;
  /** 原始文件路径（可选） */
  filePath: string;
  /** 追踪 ID（可选） */
  trackId: string;
  /** 加载引擎："native"（python-docx）/ "docling"（默认 "native"） */
  loadingEngine: string;
}

export interface LoadDocxOutput {
  /** 提取的纯文本内容 */
  content: string;
  /** 回显文件名 */
  fileName: string;
  /** 回显文件路径 */
  filePath: string;
  /** 内容 MD5 hash（用于去重） */
  contentHash: string;
  /** 提取文本长度 */
  contentLength: number;
  /** 错误信息（空字符串=成功） */
  errorMessage: string;
}

function createBaseChunkingInput(): ChunkingInput {
  return {
    content: "",
    tokenizer: new Uint8Array(0),
    chunkTokenSize: 0,
    chunkOverlapTokenSize: 0,
    splitByCharacter: "",
    splitByCharacterOnly: false,
  };
}

export const ChunkingInput: MessageFns<ChunkingInput> = {
  encode(message: ChunkingInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.tokenizer.length !== 0) {
      writer.uint32(18).bytes(message.tokenizer);
    }
    if (message.chunkTokenSize !== 0) {
      writer.uint32(24).int32(message.chunkTokenSize);
    }
    if (message.chunkOverlapTokenSize !== 0) {
      writer.uint32(32).int32(message.chunkOverlapTokenSize);
    }
    if (message.splitByCharacter !== "") {
      writer.uint32(42).string(message.splitByCharacter);
    }
    if (message.splitByCharacterOnly !== false) {
      writer.uint32(48).bool(message.splitByCharacterOnly);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChunkingInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChunkingInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenizer = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.chunkTokenSize = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.chunkOverlapTokenSize = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.splitByCharacter = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.splitByCharacterOnly = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChunkingInput>, I>>(base?: I): ChunkingInput {
    return ChunkingInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChunkingInput>, I>>(object: I): ChunkingInput {
    const message = createBaseChunkingInput();
    message.content = object.content ?? "";
    message.tokenizer = object.tokenizer ?? new Uint8Array(0);
    message.chunkTokenSize = object.chunkTokenSize ?? 0;
    message.chunkOverlapTokenSize = object.chunkOverlapTokenSize ?? 0;
    message.splitByCharacter = object.splitByCharacter ?? "";
    message.splitByCharacterOnly = object.splitByCharacterOnly ?? false;
    return message;
  },
};

function createBaseChunkingOutput(): ChunkingOutput {
  return { chunks: [] };
}

export const ChunkingOutput: MessageFns<ChunkingOutput> = {
  encode(message: ChunkingOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.chunks) {
      ChunkItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChunkingOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChunkingOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chunks.push(ChunkItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChunkingOutput>, I>>(base?: I): ChunkingOutput {
    return ChunkingOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChunkingOutput>, I>>(object: I): ChunkingOutput {
    const message = createBaseChunkingOutput();
    message.chunks = object.chunks?.map((e) => ChunkItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChunkItem(): ChunkItem {
  return { content: "", tokens: 0, chunkOrderIndex: 0 };
}

export const ChunkItem: MessageFns<ChunkItem> = {
  encode(message: ChunkItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.tokens !== 0) {
      writer.uint32(16).int32(message.tokens);
    }
    if (message.chunkOrderIndex !== 0) {
      writer.uint32(24).int32(message.chunkOrderIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChunkItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChunkItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tokens = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.chunkOrderIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChunkItem>, I>>(base?: I): ChunkItem {
    return ChunkItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChunkItem>, I>>(object: I): ChunkItem {
    const message = createBaseChunkItem();
    message.content = object.content ?? "";
    message.tokens = object.tokens ?? 0;
    message.chunkOrderIndex = object.chunkOrderIndex ?? 0;
    return message;
  },
};

function createBaseEmbeddingInput(): EmbeddingInput {
  return { texts: [] };
}

export const EmbeddingInput: MessageFns<EmbeddingInput> = {
  encode(message: EmbeddingInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.texts) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbeddingInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbeddingInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.texts.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EmbeddingInput>, I>>(base?: I): EmbeddingInput {
    return EmbeddingInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmbeddingInput>, I>>(object: I): EmbeddingInput {
    const message = createBaseEmbeddingInput();
    message.texts = object.texts?.map((e) => e) || [];
    return message;
  },
};

function createBaseEmbeddingOutput(): EmbeddingOutput {
  return { embeddings: [] };
}

export const EmbeddingOutput: MessageFns<EmbeddingOutput> = {
  encode(message: EmbeddingOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.embeddings) {
      EmbeddingVector.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbeddingOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbeddingOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.embeddings.push(EmbeddingVector.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EmbeddingOutput>, I>>(base?: I): EmbeddingOutput {
    return EmbeddingOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmbeddingOutput>, I>>(object: I): EmbeddingOutput {
    const message = createBaseEmbeddingOutput();
    message.embeddings = object.embeddings?.map((e) => EmbeddingVector.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOcrInput(): OcrInput {
  return { image: new Uint8Array(0), language: "" };
}

export const OcrInput: MessageFns<OcrInput> = {
  encode(message: OcrInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.image.length !== 0) {
      writer.uint32(10).bytes(message.image);
    }
    if (message.language !== "") {
      writer.uint32(18).string(message.language);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OcrInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOcrInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.image = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.language = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OcrInput>, I>>(base?: I): OcrInput {
    return OcrInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OcrInput>, I>>(object: I): OcrInput {
    const message = createBaseOcrInput();
    message.image = object.image ?? new Uint8Array(0);
    message.language = object.language ?? "";
    return message;
  },
};

function createBaseOcrOutput(): OcrOutput {
  return { text: "" };
}

export const OcrOutput: MessageFns<OcrOutput> = {
  encode(message: OcrOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OcrOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOcrOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OcrOutput>, I>>(base?: I): OcrOutput {
    return OcrOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OcrOutput>, I>>(object: I): OcrOutput {
    const message = createBaseOcrOutput();
    message.text = object.text ?? "";
    return message;
  },
};

function createBaseLoadTextInput(): LoadTextInput {
  return { fileContent: new Uint8Array(0), fileName: "", filePath: "", trackId: "" };
}

export const LoadTextInput: MessageFns<LoadTextInput> = {
  encode(message: LoadTextInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileContent.length !== 0) {
      writer.uint32(10).bytes(message.fileContent);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    if (message.filePath !== "") {
      writer.uint32(26).string(message.filePath);
    }
    if (message.trackId !== "") {
      writer.uint32(34).string(message.trackId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadTextInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadTextInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileContent = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.trackId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<LoadTextInput>, I>>(base?: I): LoadTextInput {
    return LoadTextInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadTextInput>, I>>(object: I): LoadTextInput {
    const message = createBaseLoadTextInput();
    message.fileContent = object.fileContent ?? new Uint8Array(0);
    message.fileName = object.fileName ?? "";
    message.filePath = object.filePath ?? "";
    message.trackId = object.trackId ?? "";
    return message;
  },
};

function createBaseLoadTextOutput(): LoadTextOutput {
  return { content: "", fileName: "", filePath: "", contentHash: "", contentLength: 0, errorMessage: "" };
}

export const LoadTextOutput: MessageFns<LoadTextOutput> = {
  encode(message: LoadTextOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    if (message.filePath !== "") {
      writer.uint32(26).string(message.filePath);
    }
    if (message.contentHash !== "") {
      writer.uint32(34).string(message.contentHash);
    }
    if (message.contentLength !== 0) {
      writer.uint32(40).int64(message.contentLength);
    }
    if (message.errorMessage !== "") {
      writer.uint32(50).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadTextOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadTextOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.contentLength = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<LoadTextOutput>, I>>(base?: I): LoadTextOutput {
    return LoadTextOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadTextOutput>, I>>(object: I): LoadTextOutput {
    const message = createBaseLoadTextOutput();
    message.content = object.content ?? "";
    message.fileName = object.fileName ?? "";
    message.filePath = object.filePath ?? "";
    message.contentHash = object.contentHash ?? "";
    message.contentLength = object.contentLength ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseLoadPdfInput(): LoadPdfInput {
  return {
    fileContent: new Uint8Array(0),
    fileName: "",
    filePath: "",
    trackId: "",
    loadingEngine: "",
    decryptPassword: "",
  };
}

export const LoadPdfInput: MessageFns<LoadPdfInput> = {
  encode(message: LoadPdfInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileContent.length !== 0) {
      writer.uint32(10).bytes(message.fileContent);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    if (message.filePath !== "") {
      writer.uint32(26).string(message.filePath);
    }
    if (message.trackId !== "") {
      writer.uint32(34).string(message.trackId);
    }
    if (message.loadingEngine !== "") {
      writer.uint32(42).string(message.loadingEngine);
    }
    if (message.decryptPassword !== "") {
      writer.uint32(50).string(message.decryptPassword);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadPdfInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadPdfInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileContent = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.trackId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.loadingEngine = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.decryptPassword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<LoadPdfInput>, I>>(base?: I): LoadPdfInput {
    return LoadPdfInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadPdfInput>, I>>(object: I): LoadPdfInput {
    const message = createBaseLoadPdfInput();
    message.fileContent = object.fileContent ?? new Uint8Array(0);
    message.fileName = object.fileName ?? "";
    message.filePath = object.filePath ?? "";
    message.trackId = object.trackId ?? "";
    message.loadingEngine = object.loadingEngine ?? "";
    message.decryptPassword = object.decryptPassword ?? "";
    return message;
  },
};

function createBaseLoadPdfOutput(): LoadPdfOutput {
  return { content: "", fileName: "", filePath: "", contentHash: "", contentLength: 0, errorMessage: "" };
}

export const LoadPdfOutput: MessageFns<LoadPdfOutput> = {
  encode(message: LoadPdfOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    if (message.filePath !== "") {
      writer.uint32(26).string(message.filePath);
    }
    if (message.contentHash !== "") {
      writer.uint32(34).string(message.contentHash);
    }
    if (message.contentLength !== 0) {
      writer.uint32(40).int64(message.contentLength);
    }
    if (message.errorMessage !== "") {
      writer.uint32(50).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadPdfOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadPdfOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.contentLength = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<LoadPdfOutput>, I>>(base?: I): LoadPdfOutput {
    return LoadPdfOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadPdfOutput>, I>>(object: I): LoadPdfOutput {
    const message = createBaseLoadPdfOutput();
    message.content = object.content ?? "";
    message.fileName = object.fileName ?? "";
    message.filePath = object.filePath ?? "";
    message.contentHash = object.contentHash ?? "";
    message.contentLength = object.contentLength ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseLoadDocxInput(): LoadDocxInput {
  return { fileContent: new Uint8Array(0), fileName: "", filePath: "", trackId: "", loadingEngine: "" };
}

export const LoadDocxInput: MessageFns<LoadDocxInput> = {
  encode(message: LoadDocxInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileContent.length !== 0) {
      writer.uint32(10).bytes(message.fileContent);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    if (message.filePath !== "") {
      writer.uint32(26).string(message.filePath);
    }
    if (message.trackId !== "") {
      writer.uint32(34).string(message.trackId);
    }
    if (message.loadingEngine !== "") {
      writer.uint32(42).string(message.loadingEngine);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadDocxInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadDocxInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileContent = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.trackId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.loadingEngine = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<LoadDocxInput>, I>>(base?: I): LoadDocxInput {
    return LoadDocxInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadDocxInput>, I>>(object: I): LoadDocxInput {
    const message = createBaseLoadDocxInput();
    message.fileContent = object.fileContent ?? new Uint8Array(0);
    message.fileName = object.fileName ?? "";
    message.filePath = object.filePath ?? "";
    message.trackId = object.trackId ?? "";
    message.loadingEngine = object.loadingEngine ?? "";
    return message;
  },
};

function createBaseLoadDocxOutput(): LoadDocxOutput {
  return { content: "", fileName: "", filePath: "", contentHash: "", contentLength: 0, errorMessage: "" };
}

export const LoadDocxOutput: MessageFns<LoadDocxOutput> = {
  encode(message: LoadDocxOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.fileName !== "") {
      writer.uint32(18).string(message.fileName);
    }
    if (message.filePath !== "") {
      writer.uint32(26).string(message.filePath);
    }
    if (message.contentHash !== "") {
      writer.uint32(34).string(message.contentHash);
    }
    if (message.contentLength !== 0) {
      writer.uint32(40).int64(message.contentLength);
    }
    if (message.errorMessage !== "") {
      writer.uint32(50).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadDocxOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadDocxOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.contentLength = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<LoadDocxOutput>, I>>(base?: I): LoadDocxOutput {
    return LoadDocxOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadDocxOutput>, I>>(object: I): LoadDocxOutput {
    const message = createBaseLoadDocxOutput();
    message.content = object.content ?? "";
    message.fileName = object.fileName ?? "";
    message.filePath = object.filePath ?? "";
    message.contentHash = object.contentHash ?? "";
    message.contentLength = object.contentLength ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
