// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: rag/insert.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { EmbeddingVector } from "../index/builder";

export const protobufPackage = "lightrag.eventbus.topics.v1";

export interface ChunkingInput {
  /** 原始文档内容 */
  content: string;
  /** 序列化的 Tiktoken tokenizer */
  tokenizer: Uint8Array;
  /** chunk token 大小 (默认 1200) */
  chunkTokenSize: number;
  /** 重叠 token 数 (默认 100) */
  chunkOverlapTokenSize: number;
  /** 分隔符 */
  splitByCharacter: string;
  /** 仅按字符分割 (默认 false) */
  splitByCharacterOnly: boolean;
}

export interface ChunkingOutput {
  /** 分块结果列表 */
  chunks: ChunkItem[];
}

export interface ChunkItem {
  /** chunk 文本内容 */
  content: string;
  /** token 数量 */
  tokens: number;
  /** chunk 在文档中的序号 */
  chunkOrderIndex: number;
}

export interface EmbeddingInput {
  /** 待嵌入的文本列表 */
  texts: string[];
}

export interface EmbeddingOutput {
  /** 嵌入结果列表 (与输入 texts 顺序一一对应) */
  embeddings: EmbeddingVector[];
}

export interface OcrInput {
  /** 图片二进制数据 */
  image: Uint8Array;
  /** OCR 语言 (默认 auto) */
  language: string;
}

export interface OcrOutput {
  /** OCR 识别的文本 */
  text: string;
}

function createBaseChunkingInput(): ChunkingInput {
  return {
    content: "",
    tokenizer: new Uint8Array(0),
    chunkTokenSize: 0,
    chunkOverlapTokenSize: 0,
    splitByCharacter: "",
    splitByCharacterOnly: false,
  };
}

export const ChunkingInput: MessageFns<ChunkingInput> = {
  encode(message: ChunkingInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.tokenizer.length !== 0) {
      writer.uint32(18).bytes(message.tokenizer);
    }
    if (message.chunkTokenSize !== 0) {
      writer.uint32(24).int32(message.chunkTokenSize);
    }
    if (message.chunkOverlapTokenSize !== 0) {
      writer.uint32(32).int32(message.chunkOverlapTokenSize);
    }
    if (message.splitByCharacter !== "") {
      writer.uint32(42).string(message.splitByCharacter);
    }
    if (message.splitByCharacterOnly !== false) {
      writer.uint32(48).bool(message.splitByCharacterOnly);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChunkingInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChunkingInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenizer = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.chunkTokenSize = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.chunkOverlapTokenSize = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.splitByCharacter = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.splitByCharacterOnly = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChunkingInput>, I>>(base?: I): ChunkingInput {
    return ChunkingInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChunkingInput>, I>>(object: I): ChunkingInput {
    const message = createBaseChunkingInput();
    message.content = object.content ?? "";
    message.tokenizer = object.tokenizer ?? new Uint8Array(0);
    message.chunkTokenSize = object.chunkTokenSize ?? 0;
    message.chunkOverlapTokenSize = object.chunkOverlapTokenSize ?? 0;
    message.splitByCharacter = object.splitByCharacter ?? "";
    message.splitByCharacterOnly = object.splitByCharacterOnly ?? false;
    return message;
  },
};

function createBaseChunkingOutput(): ChunkingOutput {
  return { chunks: [] };
}

export const ChunkingOutput: MessageFns<ChunkingOutput> = {
  encode(message: ChunkingOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.chunks) {
      ChunkItem.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChunkingOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChunkingOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chunks.push(ChunkItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChunkingOutput>, I>>(base?: I): ChunkingOutput {
    return ChunkingOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChunkingOutput>, I>>(object: I): ChunkingOutput {
    const message = createBaseChunkingOutput();
    message.chunks = object.chunks?.map((e) => ChunkItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseChunkItem(): ChunkItem {
  return { content: "", tokens: 0, chunkOrderIndex: 0 };
}

export const ChunkItem: MessageFns<ChunkItem> = {
  encode(message: ChunkItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.tokens !== 0) {
      writer.uint32(16).int32(message.tokens);
    }
    if (message.chunkOrderIndex !== 0) {
      writer.uint32(24).int32(message.chunkOrderIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChunkItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChunkItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tokens = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.chunkOrderIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ChunkItem>, I>>(base?: I): ChunkItem {
    return ChunkItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChunkItem>, I>>(object: I): ChunkItem {
    const message = createBaseChunkItem();
    message.content = object.content ?? "";
    message.tokens = object.tokens ?? 0;
    message.chunkOrderIndex = object.chunkOrderIndex ?? 0;
    return message;
  },
};

function createBaseEmbeddingInput(): EmbeddingInput {
  return { texts: [] };
}

export const EmbeddingInput: MessageFns<EmbeddingInput> = {
  encode(message: EmbeddingInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.texts) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbeddingInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbeddingInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.texts.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EmbeddingInput>, I>>(base?: I): EmbeddingInput {
    return EmbeddingInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmbeddingInput>, I>>(object: I): EmbeddingInput {
    const message = createBaseEmbeddingInput();
    message.texts = object.texts?.map((e) => e) || [];
    return message;
  },
};

function createBaseEmbeddingOutput(): EmbeddingOutput {
  return { embeddings: [] };
}

export const EmbeddingOutput: MessageFns<EmbeddingOutput> = {
  encode(message: EmbeddingOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.embeddings) {
      EmbeddingVector.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmbeddingOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmbeddingOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.embeddings.push(EmbeddingVector.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EmbeddingOutput>, I>>(base?: I): EmbeddingOutput {
    return EmbeddingOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmbeddingOutput>, I>>(object: I): EmbeddingOutput {
    const message = createBaseEmbeddingOutput();
    message.embeddings = object.embeddings?.map((e) => EmbeddingVector.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOcrInput(): OcrInput {
  return { image: new Uint8Array(0), language: "" };
}

export const OcrInput: MessageFns<OcrInput> = {
  encode(message: OcrInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.image.length !== 0) {
      writer.uint32(10).bytes(message.image);
    }
    if (message.language !== "") {
      writer.uint32(18).string(message.language);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OcrInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOcrInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.image = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.language = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OcrInput>, I>>(base?: I): OcrInput {
    return OcrInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OcrInput>, I>>(object: I): OcrInput {
    const message = createBaseOcrInput();
    message.image = object.image ?? new Uint8Array(0);
    message.language = object.language ?? "";
    return message;
  },
};

function createBaseOcrOutput(): OcrOutput {
  return { text: "" };
}

export const OcrOutput: MessageFns<OcrOutput> = {
  encode(message: OcrOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OcrOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOcrOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OcrOutput>, I>>(base?: I): OcrOutput {
    return OcrOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OcrOutput>, I>>(object: I): OcrOutput {
    const message = createBaseOcrOutput();
    message.text = object.text ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
