# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm/completion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm/completion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14llm/completion.proto\x12\x1blightrag.eventbus.topics.v1\"\xdd\x02\n\rCompleteInput\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x15\n\rsystem_prompt\x18\x02 \x01(\t\x12\x42\n\x10history_messages\x18\x03 \x03(\x0b\x32(.lightrag.eventbus.topics.v1.ChatMessage\x12\x12\n\nenable_cot\x18\x04 \x01(\x08\x12\x0e\n\x06stream\x18\x05 \x01(\x08\x12\x10\n\x08priority\x18\x06 \x01(\x05\x12\x12\n\ncache_type\x18\x07 \x01(\t\x12\x10\n\x08\x63hunk_id\x18\x08 \x01(\t\x12Q\n\x0c\x65xtra_kwargs\x18\t \x03(\x0b\x32;.lightrag.eventbus.topics.v1.CompleteInput.ExtraKwargsEntry\x1a\x32\n\x10\x45xtraKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"F\n\x0e\x43ompleteOutput\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x13\n\x0btoken_count\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\tBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm.completion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topics'
  _globals['_COMPLETEINPUT_EXTRAKWARGSENTRY']._loaded_options = None
  _globals['_COMPLETEINPUT_EXTRAKWARGSENTRY']._serialized_options = b'8\001'
  _globals['_COMPLETEINPUT']._serialized_start=54
  _globals['_COMPLETEINPUT']._serialized_end=403
  _globals['_COMPLETEINPUT_EXTRAKWARGSENTRY']._serialized_start=353
  _globals['_COMPLETEINPUT_EXTRAKWARGSENTRY']._serialized_end=403
  _globals['_CHATMESSAGE']._serialized_start=405
  _globals['_CHATMESSAGE']._serialized_end=449
  _globals['_COMPLETEOUTPUT']._serialized_start=451
  _globals['_COMPLETEOUTPUT']._serialized_end=521
# @@protoc_insertion_point(module_scope)
