// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: kg/merge.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lightrag.eventbus.topics.v1";

export interface EntityMergeInput {
  /** 实体名称（合并 key） */
  entityName: string;
  /** 新提取的实体数据列表 */
  newEntities: EntityData[];
  /** 合并配置 */
  mergeConfig: MergeConfig | undefined;
}

export interface EntityData {
  /** 实体类型 */
  entityType: string;
  /** 实体描述 */
  description: string;
  /** 来源 chunk ID */
  sourceId: string;
  /** 来源文件路径 */
  filePath: string;
  /** 提取时间戳 */
  timestamp: number;
}

export interface MergeConfig {
  /** source_id 最大保留数（默认 20） */
  maxSourceIds: number;
  /** 截断策略："FIFO" 或 "KEEP"（默认 "FIFO"） */
  limitMethod: string;
  /** LLM 摘要最大 token 数 */
  summaryMaxTokens: number;
  /** 摘要上下文窗口 token 数 */
  summaryContextSize: number;
  /** 超过此描述数强制 LLM 摘要 */
  forceLlmSummaryOnMerge: number;
  /** 摘要语言（如 "Chinese", "English"） */
  language: string;
  /** file_path 最大保留数 */
  maxFilePaths: number;
}

export interface EntityMergeOutput {
  /** 回显实体名 */
  entityName: string;
  /** 最终实体类型（众数） */
  entityType: string;
  /** 合并后的描述（LLM 摘要或拼接） */
  description: string;
  /** 合并后的 source_id（GRAPH_FIELD_SEP 分隔） */
  sourceId: string;
  /** 合并后的 file_path */
  filePath: string;
  /** 截断信息（如 "FIFO 20/35"） */
  truncate: string;
  /** 向量存储内容："{entity_name}\n{description}" */
  content: string;
  /** 完整未截断的 source_id 列表 */
  fullSourceIds: string[];
  /** 是否调用了 LLM 摘要 */
  llmUsed: boolean;
}

export interface RelationMergeInput {
  /** 源实体名称 */
  srcId: string;
  /** 目标实体名称 */
  tgtId: string;
  /** 新提取的关系数据列表 */
  newRelations: RelationData[];
  /** 合并配置（复用同一结构） */
  mergeConfig: MergeConfig | undefined;
}

export interface RelationData {
  /** 关系权重 */
  weight: number;
  /** 关系描述 */
  description: string;
  /** 关键词（逗号分隔） */
  keywords: string;
  /** 来源 chunk ID */
  sourceId: string;
  /** 来源文件路径 */
  filePath: string;
  /** 提取时间戳 */
  timestamp: number;
}

export interface RelationMergeOutput {
  /** 源实体 */
  srcId: string;
  /** 目标实体 */
  tgtId: string;
  /** 合并后权重（累加） */
  weight: number;
  /** 合并后的描述（LLM 摘要或拼接） */
  description: string;
  /** 合并后的关键词（排序去重） */
  keywords: string;
  /** 合并后的 source_id */
  sourceId: string;
  /** 合并后的 file_path */
  filePath: string;
  /** 截断信息 */
  truncate: string;
  /** 向量存储内容："{keywords}\t{src}\n{tgt}\n{description}" */
  content: string;
  /** 完整未截断的 source_id 列表 */
  fullSourceIds: string[];
  /** 是否调用了 LLM 摘要 */
  llmUsed: boolean;
  /** 新创建的实体（关系合并的副作用） */
  createdEntities: CreatedEntity[];
}

export interface CreatedEntity {
  entityName: string;
  /** 通常 "UNKNOWN" */
  entityType: string;
  description: string;
  sourceId: string;
  filePath: string;
  /** 向量存储内容 */
  content: string;
}

function createBaseEntityMergeInput(): EntityMergeInput {
  return { entityName: "", newEntities: [], mergeConfig: undefined };
}

export const EntityMergeInput: MessageFns<EntityMergeInput> = {
  encode(message: EntityMergeInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityName !== "") {
      writer.uint32(10).string(message.entityName);
    }
    for (const v of message.newEntities) {
      EntityData.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.mergeConfig !== undefined) {
      MergeConfig.encode(message.mergeConfig, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityMergeInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityMergeInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.newEntities.push(EntityData.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mergeConfig = MergeConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EntityMergeInput>, I>>(base?: I): EntityMergeInput {
    return EntityMergeInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EntityMergeInput>, I>>(object: I): EntityMergeInput {
    const message = createBaseEntityMergeInput();
    message.entityName = object.entityName ?? "";
    message.newEntities = object.newEntities?.map((e) => EntityData.fromPartial(e)) || [];
    message.mergeConfig = (object.mergeConfig !== undefined && object.mergeConfig !== null)
      ? MergeConfig.fromPartial(object.mergeConfig)
      : undefined;
    return message;
  },
};

function createBaseEntityData(): EntityData {
  return { entityType: "", description: "", sourceId: "", filePath: "", timestamp: 0 };
}

export const EntityData: MessageFns<EntityData> = {
  encode(message: EntityData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityType !== "") {
      writer.uint32(10).string(message.entityType);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.sourceId !== "") {
      writer.uint32(26).string(message.sourceId);
    }
    if (message.filePath !== "") {
      writer.uint32(34).string(message.filePath);
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sourceId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EntityData>, I>>(base?: I): EntityData {
    return EntityData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EntityData>, I>>(object: I): EntityData {
    const message = createBaseEntityData();
    message.entityType = object.entityType ?? "";
    message.description = object.description ?? "";
    message.sourceId = object.sourceId ?? "";
    message.filePath = object.filePath ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseMergeConfig(): MergeConfig {
  return {
    maxSourceIds: 0,
    limitMethod: "",
    summaryMaxTokens: 0,
    summaryContextSize: 0,
    forceLlmSummaryOnMerge: 0,
    language: "",
    maxFilePaths: 0,
  };
}

export const MergeConfig: MessageFns<MergeConfig> = {
  encode(message: MergeConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxSourceIds !== 0) {
      writer.uint32(8).int32(message.maxSourceIds);
    }
    if (message.limitMethod !== "") {
      writer.uint32(18).string(message.limitMethod);
    }
    if (message.summaryMaxTokens !== 0) {
      writer.uint32(24).int32(message.summaryMaxTokens);
    }
    if (message.summaryContextSize !== 0) {
      writer.uint32(32).int32(message.summaryContextSize);
    }
    if (message.forceLlmSummaryOnMerge !== 0) {
      writer.uint32(40).int32(message.forceLlmSummaryOnMerge);
    }
    if (message.language !== "") {
      writer.uint32(50).string(message.language);
    }
    if (message.maxFilePaths !== 0) {
      writer.uint32(56).int32(message.maxFilePaths);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MergeConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMergeConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxSourceIds = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.limitMethod = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.summaryMaxTokens = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.summaryContextSize = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.forceLlmSummaryOnMerge = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.maxFilePaths = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MergeConfig>, I>>(base?: I): MergeConfig {
    return MergeConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MergeConfig>, I>>(object: I): MergeConfig {
    const message = createBaseMergeConfig();
    message.maxSourceIds = object.maxSourceIds ?? 0;
    message.limitMethod = object.limitMethod ?? "";
    message.summaryMaxTokens = object.summaryMaxTokens ?? 0;
    message.summaryContextSize = object.summaryContextSize ?? 0;
    message.forceLlmSummaryOnMerge = object.forceLlmSummaryOnMerge ?? 0;
    message.language = object.language ?? "";
    message.maxFilePaths = object.maxFilePaths ?? 0;
    return message;
  },
};

function createBaseEntityMergeOutput(): EntityMergeOutput {
  return {
    entityName: "",
    entityType: "",
    description: "",
    sourceId: "",
    filePath: "",
    truncate: "",
    content: "",
    fullSourceIds: [],
    llmUsed: false,
  };
}

export const EntityMergeOutput: MessageFns<EntityMergeOutput> = {
  encode(message: EntityMergeOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityName !== "") {
      writer.uint32(10).string(message.entityName);
    }
    if (message.entityType !== "") {
      writer.uint32(18).string(message.entityType);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.sourceId !== "") {
      writer.uint32(34).string(message.sourceId);
    }
    if (message.filePath !== "") {
      writer.uint32(42).string(message.filePath);
    }
    if (message.truncate !== "") {
      writer.uint32(50).string(message.truncate);
    }
    if (message.content !== "") {
      writer.uint32(58).string(message.content);
    }
    for (const v of message.fullSourceIds) {
      writer.uint32(66).string(v!);
    }
    if (message.llmUsed !== false) {
      writer.uint32(72).bool(message.llmUsed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityMergeOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityMergeOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entityType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourceId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.truncate = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.fullSourceIds.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.llmUsed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EntityMergeOutput>, I>>(base?: I): EntityMergeOutput {
    return EntityMergeOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EntityMergeOutput>, I>>(object: I): EntityMergeOutput {
    const message = createBaseEntityMergeOutput();
    message.entityName = object.entityName ?? "";
    message.entityType = object.entityType ?? "";
    message.description = object.description ?? "";
    message.sourceId = object.sourceId ?? "";
    message.filePath = object.filePath ?? "";
    message.truncate = object.truncate ?? "";
    message.content = object.content ?? "";
    message.fullSourceIds = object.fullSourceIds?.map((e) => e) || [];
    message.llmUsed = object.llmUsed ?? false;
    return message;
  },
};

function createBaseRelationMergeInput(): RelationMergeInput {
  return { srcId: "", tgtId: "", newRelations: [], mergeConfig: undefined };
}

export const RelationMergeInput: MessageFns<RelationMergeInput> = {
  encode(message: RelationMergeInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.srcId !== "") {
      writer.uint32(10).string(message.srcId);
    }
    if (message.tgtId !== "") {
      writer.uint32(18).string(message.tgtId);
    }
    for (const v of message.newRelations) {
      RelationData.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.mergeConfig !== undefined) {
      MergeConfig.encode(message.mergeConfig, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelationMergeInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationMergeInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.srcId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tgtId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newRelations.push(RelationData.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.mergeConfig = MergeConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RelationMergeInput>, I>>(base?: I): RelationMergeInput {
    return RelationMergeInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationMergeInput>, I>>(object: I): RelationMergeInput {
    const message = createBaseRelationMergeInput();
    message.srcId = object.srcId ?? "";
    message.tgtId = object.tgtId ?? "";
    message.newRelations = object.newRelations?.map((e) => RelationData.fromPartial(e)) || [];
    message.mergeConfig = (object.mergeConfig !== undefined && object.mergeConfig !== null)
      ? MergeConfig.fromPartial(object.mergeConfig)
      : undefined;
    return message;
  },
};

function createBaseRelationData(): RelationData {
  return { weight: 0, description: "", keywords: "", sourceId: "", filePath: "", timestamp: 0 };
}

export const RelationData: MessageFns<RelationData> = {
  encode(message: RelationData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.weight !== 0) {
      writer.uint32(13).float(message.weight);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.keywords !== "") {
      writer.uint32(26).string(message.keywords);
    }
    if (message.sourceId !== "") {
      writer.uint32(34).string(message.sourceId);
    }
    if (message.filePath !== "") {
      writer.uint32(42).string(message.filePath);
    }
    if (message.timestamp !== 0) {
      writer.uint32(48).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelationData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 13) {
            break;
          }

          message.weight = reader.float();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.keywords = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourceId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RelationData>, I>>(base?: I): RelationData {
    return RelationData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationData>, I>>(object: I): RelationData {
    const message = createBaseRelationData();
    message.weight = object.weight ?? 0;
    message.description = object.description ?? "";
    message.keywords = object.keywords ?? "";
    message.sourceId = object.sourceId ?? "";
    message.filePath = object.filePath ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseRelationMergeOutput(): RelationMergeOutput {
  return {
    srcId: "",
    tgtId: "",
    weight: 0,
    description: "",
    keywords: "",
    sourceId: "",
    filePath: "",
    truncate: "",
    content: "",
    fullSourceIds: [],
    llmUsed: false,
    createdEntities: [],
  };
}

export const RelationMergeOutput: MessageFns<RelationMergeOutput> = {
  encode(message: RelationMergeOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.srcId !== "") {
      writer.uint32(10).string(message.srcId);
    }
    if (message.tgtId !== "") {
      writer.uint32(18).string(message.tgtId);
    }
    if (message.weight !== 0) {
      writer.uint32(29).float(message.weight);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.keywords !== "") {
      writer.uint32(42).string(message.keywords);
    }
    if (message.sourceId !== "") {
      writer.uint32(50).string(message.sourceId);
    }
    if (message.filePath !== "") {
      writer.uint32(58).string(message.filePath);
    }
    if (message.truncate !== "") {
      writer.uint32(66).string(message.truncate);
    }
    if (message.content !== "") {
      writer.uint32(74).string(message.content);
    }
    for (const v of message.fullSourceIds) {
      writer.uint32(82).string(v!);
    }
    if (message.llmUsed !== false) {
      writer.uint32(88).bool(message.llmUsed);
    }
    for (const v of message.createdEntities) {
      CreatedEntity.encode(v!, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RelationMergeOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelationMergeOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.srcId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tgtId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.weight = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.keywords = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.sourceId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.truncate = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.fullSourceIds.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.llmUsed = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.createdEntities.push(CreatedEntity.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RelationMergeOutput>, I>>(base?: I): RelationMergeOutput {
    return RelationMergeOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RelationMergeOutput>, I>>(object: I): RelationMergeOutput {
    const message = createBaseRelationMergeOutput();
    message.srcId = object.srcId ?? "";
    message.tgtId = object.tgtId ?? "";
    message.weight = object.weight ?? 0;
    message.description = object.description ?? "";
    message.keywords = object.keywords ?? "";
    message.sourceId = object.sourceId ?? "";
    message.filePath = object.filePath ?? "";
    message.truncate = object.truncate ?? "";
    message.content = object.content ?? "";
    message.fullSourceIds = object.fullSourceIds?.map((e) => e) || [];
    message.llmUsed = object.llmUsed ?? false;
    message.createdEntities = object.createdEntities?.map((e) => CreatedEntity.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreatedEntity(): CreatedEntity {
  return { entityName: "", entityType: "", description: "", sourceId: "", filePath: "", content: "" };
}

export const CreatedEntity: MessageFns<CreatedEntity> = {
  encode(message: CreatedEntity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityName !== "") {
      writer.uint32(10).string(message.entityName);
    }
    if (message.entityType !== "") {
      writer.uint32(18).string(message.entityType);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.sourceId !== "") {
      writer.uint32(34).string(message.sourceId);
    }
    if (message.filePath !== "") {
      writer.uint32(42).string(message.filePath);
    }
    if (message.content !== "") {
      writer.uint32(50).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatedEntity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatedEntity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entityType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sourceId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.filePath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CreatedEntity>, I>>(base?: I): CreatedEntity {
    return CreatedEntity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreatedEntity>, I>>(object: I): CreatedEntity {
    const message = createBaseCreatedEntity();
    message.entityName = object.entityName ?? "";
    message.entityType = object.entityType ?? "";
    message.description = object.description ?? "";
    message.sourceId = object.sourceId ?? "";
    message.filePath = object.filePath ?? "";
    message.content = object.content ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
