# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: insert.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'insert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cinsert.proto\x12\x1blightrag.eventbus.topics.v1\"\xac\x01\n\rChunkingInput\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\ttokenizer\x18\x02 \x01(\x0c\x12\x18\n\x10\x63hunk_token_size\x18\x03 \x01(\x05\x12 \n\x18\x63hunk_overlap_token_size\x18\x04 \x01(\x05\x12\x1a\n\x12split_by_character\x18\x05 \x01(\t\x12\x1f\n\x17split_by_character_only\x18\x06 \x01(\x08\"H\n\x0e\x43hunkingOutput\x12\x36\n\x06\x63hunks\x18\x01 \x03(\x0b\x32&.lightrag.eventbus.topics.v1.ChunkItem\"G\n\tChunkItem\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06tokens\x18\x02 \x01(\x05\x12\x19\n\x11\x63hunk_order_index\x18\x03 \x01(\x05\"b\n\x0e\x45mbeddingInput\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x15\n\rembedding_dim\x18\x03 \x01(\x05\x12\x16\n\x0emax_token_size\x18\x04 \x01(\x05\"S\n\x0f\x45mbeddingOutput\x12@\n\nembeddings\x18\x01 \x03(\x0b\x32,.lightrag.eventbus.topics.v1.EmbeddingVector\"!\n\x0f\x45mbeddingVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"+\n\x08OcrInput\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08language\x18\x02 \x01(\t\"\x19\n\tOcrOutput\x12\x0c\n\x04text\x18\x01 \x01(\tBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'insert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topics'
  _globals['_CHUNKINGINPUT']._serialized_start=46
  _globals['_CHUNKINGINPUT']._serialized_end=218
  _globals['_CHUNKINGOUTPUT']._serialized_start=220
  _globals['_CHUNKINGOUTPUT']._serialized_end=292
  _globals['_CHUNKITEM']._serialized_start=294
  _globals['_CHUNKITEM']._serialized_end=365
  _globals['_EMBEDDINGINPUT']._serialized_start=367
  _globals['_EMBEDDINGINPUT']._serialized_end=465
  _globals['_EMBEDDINGOUTPUT']._serialized_start=467
  _globals['_EMBEDDINGOUTPUT']._serialized_end=550
  _globals['_EMBEDDINGVECTOR']._serialized_start=552
  _globals['_EMBEDDINGVECTOR']._serialized_end=585
  _globals['_OCRINPUT']._serialized_start=587
  _globals['_OCRINPUT']._serialized_end=630
  _globals['_OCROUTPUT']._serialized_start=632
  _globals['_OCROUTPUT']._serialized_end=657
# @@protoc_insertion_point(module_scope)
