// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: llm/completion.proto

package topics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Prompt          string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                                                        // 主提示词（user role 内容）
	SystemPrompt    string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`                                                                        // 系统提示词（可选，空字符串=无）
	HistoryMessages []*ChatMessage         `protobuf:"bytes,3,rep,name=history_messages,json=historyMessages,proto3" json:"history_messages,omitempty"`                                                               // 对话历史（可选，gleaning / 多轮场景）
	EnableCot       bool                   `protobuf:"varint,4,opt,name=enable_cot,json=enableCot,proto3" json:"enable_cot,omitempty"`                                                                                // 是否启用 Chain-of-Thought（默认 false）
	Stream          bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"`                                                                                                       // 是否流式输出（默认 false）
	Priority        int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`                                                                                                   // 优先级：5=查询, 8=摘要, 10=索引（默认 10）
	CacheType       string                 `protobuf:"bytes,7,opt,name=cache_type,json=cacheType,proto3" json:"cache_type,omitempty"`                                                                                 // 缓存类型标识（如 "extract", "summary", "keywords"）
	ChunkId         string                 `protobuf:"bytes,8,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`                                                                                       // 关联的 chunk ID（用于缓存 key 生成，可选）
	ExtraKwargs     map[string]string      `protobuf:"bytes,9,rep,name=extra_kwargs,json=extraKwargs,proto3" json:"extra_kwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外参数（如 keyword_extraction=true）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteInput) Reset() {
	*x = CompleteInput{}
	mi := &file_llm_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteInput) ProtoMessage() {}

func (x *CompleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_llm_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteInput.ProtoReflect.Descriptor instead.
func (*CompleteInput) Descriptor() ([]byte, []int) {
	return file_llm_completion_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteInput) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompleteInput) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CompleteInput) GetHistoryMessages() []*ChatMessage {
	if x != nil {
		return x.HistoryMessages
	}
	return nil
}

func (x *CompleteInput) GetEnableCot() bool {
	if x != nil {
		return x.EnableCot
	}
	return false
}

func (x *CompleteInput) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *CompleteInput) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CompleteInput) GetCacheType() string {
	if x != nil {
		return x.CacheType
	}
	return ""
}

func (x *CompleteInput) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *CompleteInput) GetExtraKwargs() map[string]string {
	if x != nil {
		return x.ExtraKwargs
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // "user" 或 "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llm_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llm_completion_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CompleteOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`                        // 生成的文本响应（非流式）
	TokenCount    int32                  `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"` // 响应 token 数（可选，用于监控）
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                              // 实际使用的模型名（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOutput) Reset() {
	*x = CompleteOutput{}
	mi := &file_llm_completion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOutput) ProtoMessage() {}

func (x *CompleteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_llm_completion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOutput.ProtoReflect.Descriptor instead.
func (*CompleteOutput) Descriptor() ([]byte, []int) {
	return file_llm_completion_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteOutput) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *CompleteOutput) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *CompleteOutput) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_llm_completion_proto protoreflect.FileDescriptor

const file_llm_completion_proto_rawDesc = "" +
	"\n" +
	"\x14llm/completion.proto\x12\x1blightrag.eventbus.topics.v1\"\xce\x03\n" +
	"\rCompleteInput\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12S\n" +
	"\x10history_messages\x18\x03 \x03(\v2(.lightrag.eventbus.topics.v1.ChatMessageR\x0fhistoryMessages\x12\x1d\n" +
	"\n" +
	"enable_cot\x18\x04 \x01(\bR\tenableCot\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"cache_type\x18\a \x01(\tR\tcacheType\x12\x19\n" +
	"\bchunk_id\x18\b \x01(\tR\achunkId\x12^\n" +
	"\fextra_kwargs\x18\t \x03(\v2;.lightrag.eventbus.topics.v1.CompleteInput.ExtraKwargsEntryR\vextraKwargs\x1a>\n" +
	"\x10ExtraKwargsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"c\n" +
	"\x0eCompleteOutput\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05modelBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3"

var (
	file_llm_completion_proto_rawDescOnce sync.Once
	file_llm_completion_proto_rawDescData []byte
)

func file_llm_completion_proto_rawDescGZIP() []byte {
	file_llm_completion_proto_rawDescOnce.Do(func() {
		file_llm_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_completion_proto_rawDesc), len(file_llm_completion_proto_rawDesc)))
	})
	return file_llm_completion_proto_rawDescData
}

var file_llm_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_llm_completion_proto_goTypes = []any{
	(*CompleteInput)(nil),  // 0: lightrag.eventbus.topics.v1.CompleteInput
	(*ChatMessage)(nil),    // 1: lightrag.eventbus.topics.v1.ChatMessage
	(*CompleteOutput)(nil), // 2: lightrag.eventbus.topics.v1.CompleteOutput
	nil,                    // 3: lightrag.eventbus.topics.v1.CompleteInput.ExtraKwargsEntry
}
var file_llm_completion_proto_depIdxs = []int32{
	1, // 0: lightrag.eventbus.topics.v1.CompleteInput.history_messages:type_name -> lightrag.eventbus.topics.v1.ChatMessage
	3, // 1: lightrag.eventbus.topics.v1.CompleteInput.extra_kwargs:type_name -> lightrag.eventbus.topics.v1.CompleteInput.ExtraKwargsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_completion_proto_init() }
func file_llm_completion_proto_init() {
	if File_llm_completion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_completion_proto_rawDesc), len(file_llm_completion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llm_completion_proto_goTypes,
		DependencyIndexes: file_llm_completion_proto_depIdxs,
		MessageInfos:      file_llm_completion_proto_msgTypes,
	}.Build()
	File_llm_completion_proto = out.File
	file_llm_completion_proto_goTypes = nil
	file_llm_completion_proto_depIdxs = nil
}
