// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: embedding/embed.proto

package topics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbeddingVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // 向量浮点值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingVector) Reset() {
	*x = EmbeddingVector{}
	mi := &file_embedding_embed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingVector) ProtoMessage() {}

func (x *EmbeddingVector) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_embed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingVector.ProtoReflect.Descriptor instead.
func (*EmbeddingVector) Descriptor() ([]byte, []int) {
	return file_embedding_embed_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type EmbeddingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"` // 待嵌入的文本列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingInput) Reset() {
	*x = EmbeddingInput{}
	mi := &file_embedding_embed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingInput) ProtoMessage() {}

func (x *EmbeddingInput) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_embed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingInput.ProtoReflect.Descriptor instead.
func (*EmbeddingInput) Descriptor() ([]byte, []int) {
	return file_embedding_embed_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingInput) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type EmbeddingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbeddingVector     `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"` // 嵌入结果列表 (与输入 texts 顺序一一对应)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingOutput) Reset() {
	*x = EmbeddingOutput{}
	mi := &file_embedding_embed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingOutput) ProtoMessage() {}

func (x *EmbeddingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_embed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingOutput.ProtoReflect.Descriptor instead.
func (*EmbeddingOutput) Descriptor() ([]byte, []int) {
	return file_embedding_embed_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddingOutput) GetEmbeddings() []*EmbeddingVector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

var File_embedding_embed_proto protoreflect.FileDescriptor

const file_embedding_embed_proto_rawDesc = "" +
	"\n" +
	"\x15embedding/embed.proto\x12\x1blightrag.eventbus.topics.v1\"-\n" +
	"\x0fEmbeddingVector\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\x02B\x02\x10\x01R\x06values\"&\n" +
	"\x0eEmbeddingInput\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"_\n" +
	"\x0fEmbeddingOutput\x12L\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2,.lightrag.eventbus.topics.v1.EmbeddingVectorR\n" +
	"embeddingsBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3"

var (
	file_embedding_embed_proto_rawDescOnce sync.Once
	file_embedding_embed_proto_rawDescData []byte
)

func file_embedding_embed_proto_rawDescGZIP() []byte {
	file_embedding_embed_proto_rawDescOnce.Do(func() {
		file_embedding_embed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_embed_proto_rawDesc), len(file_embedding_embed_proto_rawDesc)))
	})
	return file_embedding_embed_proto_rawDescData
}

var file_embedding_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_embedding_embed_proto_goTypes = []any{
	(*EmbeddingVector)(nil), // 0: lightrag.eventbus.topics.v1.EmbeddingVector
	(*EmbeddingInput)(nil),  // 1: lightrag.eventbus.topics.v1.EmbeddingInput
	(*EmbeddingOutput)(nil), // 2: lightrag.eventbus.topics.v1.EmbeddingOutput
}
var file_embedding_embed_proto_depIdxs = []int32{
	0, // 0: lightrag.eventbus.topics.v1.EmbeddingOutput.embeddings:type_name -> lightrag.eventbus.topics.v1.EmbeddingVector
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_embedding_embed_proto_init() }
func file_embedding_embed_proto_init() {
	if File_embedding_embed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_embed_proto_rawDesc), len(file_embedding_embed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_embedding_embed_proto_goTypes,
		DependencyIndexes: file_embedding_embed_proto_depIdxs,
		MessageInfos:      file_embedding_embed_proto_msgTypes,
	}.Build()
	File_embedding_embed_proto = out.File
	file_embedding_embed_proto_goTypes = nil
	file_embedding_embed_proto_depIdxs = nil
}
