// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: rag/insert.proto

package topics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkingInput struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Content               string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                                               // 原始文档内容
	Tokenizer             []byte                 `protobuf:"bytes,2,opt,name=tokenizer,proto3" json:"tokenizer,omitempty"`                                                           // 序列化的 Tiktoken tokenizer
	ChunkTokenSize        int32                  `protobuf:"varint,3,opt,name=chunk_token_size,json=chunkTokenSize,proto3" json:"chunk_token_size,omitempty"`                        // chunk token 大小 (默认 1200)
	ChunkOverlapTokenSize int32                  `protobuf:"varint,4,opt,name=chunk_overlap_token_size,json=chunkOverlapTokenSize,proto3" json:"chunk_overlap_token_size,omitempty"` // 重叠 token 数 (默认 100)
	SplitByCharacter      string                 `protobuf:"bytes,5,opt,name=split_by_character,json=splitByCharacter,proto3" json:"split_by_character,omitempty"`                   // 分隔符
	SplitByCharacterOnly  bool                   `protobuf:"varint,6,opt,name=split_by_character_only,json=splitByCharacterOnly,proto3" json:"split_by_character_only,omitempty"`    // 仅按字符分割 (默认 false)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChunkingInput) Reset() {
	*x = ChunkingInput{}
	mi := &file_rag_insert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkingInput) ProtoMessage() {}

func (x *ChunkingInput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkingInput.ProtoReflect.Descriptor instead.
func (*ChunkingInput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkingInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkingInput) GetTokenizer() []byte {
	if x != nil {
		return x.Tokenizer
	}
	return nil
}

func (x *ChunkingInput) GetChunkTokenSize() int32 {
	if x != nil {
		return x.ChunkTokenSize
	}
	return 0
}

func (x *ChunkingInput) GetChunkOverlapTokenSize() int32 {
	if x != nil {
		return x.ChunkOverlapTokenSize
	}
	return 0
}

func (x *ChunkingInput) GetSplitByCharacter() string {
	if x != nil {
		return x.SplitByCharacter
	}
	return ""
}

func (x *ChunkingInput) GetSplitByCharacterOnly() bool {
	if x != nil {
		return x.SplitByCharacterOnly
	}
	return false
}

type ChunkingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ChunkItem           `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"` // 分块结果列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkingOutput) Reset() {
	*x = ChunkingOutput{}
	mi := &file_rag_insert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkingOutput) ProtoMessage() {}

func (x *ChunkingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkingOutput.ProtoReflect.Descriptor instead.
func (*ChunkingOutput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkingOutput) GetChunks() []*ChunkItem {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Content         string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                           // chunk 文本内容
	Tokens          int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`                                            // token 数量
	ChunkOrderIndex int32                  `protobuf:"varint,3,opt,name=chunk_order_index,json=chunkOrderIndex,proto3" json:"chunk_order_index,omitempty"` // chunk 在文档中的序号
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkItem) Reset() {
	*x = ChunkItem{}
	mi := &file_rag_insert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkItem) ProtoMessage() {}

func (x *ChunkItem) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkItem.ProtoReflect.Descriptor instead.
func (*ChunkItem) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkItem) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *ChunkItem) GetChunkOrderIndex() int32 {
	if x != nil {
		return x.ChunkOrderIndex
	}
	return 0
}

type EmbeddingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"` // 待嵌入的文本列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingInput) Reset() {
	*x = EmbeddingInput{}
	mi := &file_rag_insert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingInput) ProtoMessage() {}

func (x *EmbeddingInput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingInput.ProtoReflect.Descriptor instead.
func (*EmbeddingInput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{3}
}

func (x *EmbeddingInput) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type EmbeddingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbeddingVector     `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"` // 嵌入结果列表 (与输入 texts 顺序一一对应)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingOutput) Reset() {
	*x = EmbeddingOutput{}
	mi := &file_rag_insert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingOutput) ProtoMessage() {}

func (x *EmbeddingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingOutput.ProtoReflect.Descriptor instead.
func (*EmbeddingOutput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingOutput) GetEmbeddings() []*EmbeddingVector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type OcrInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`       // 图片二进制数据
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // OCR 语言 (默认 auto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrInput) Reset() {
	*x = OcrInput{}
	mi := &file_rag_insert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrInput) ProtoMessage() {}

func (x *OcrInput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrInput.ProtoReflect.Descriptor instead.
func (*OcrInput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{5}
}

func (x *OcrInput) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *OcrInput) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type OcrOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // OCR 识别的文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrOutput) Reset() {
	*x = OcrOutput{}
	mi := &file_rag_insert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrOutput) ProtoMessage() {}

func (x *OcrOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrOutput.ProtoReflect.Descriptor instead.
func (*OcrOutput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{6}
}

func (x *OcrOutput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LoadTextInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // 文件二进制内容
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // 文件名（含扩展名）
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`          // 原始文件路径（可选）
	TrackId       string                 `protobuf:"bytes,4,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`             // 追踪 ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTextInput) Reset() {
	*x = LoadTextInput{}
	mi := &file_rag_insert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTextInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTextInput) ProtoMessage() {}

func (x *LoadTextInput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTextInput.ProtoReflect.Descriptor instead.
func (*LoadTextInput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{7}
}

func (x *LoadTextInput) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *LoadTextInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LoadTextInput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoadTextInput) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type LoadTextOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                   // 提取的纯文本内容
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                 // 回显文件名
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                 // 回显文件路径
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`        // 内容 MD5 hash（用于去重）
	ContentLength int64                  `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // 提取文本长度
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`     // 错误信息（空字符串=成功）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTextOutput) Reset() {
	*x = LoadTextOutput{}
	mi := &file_rag_insert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTextOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTextOutput) ProtoMessage() {}

func (x *LoadTextOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTextOutput.ProtoReflect.Descriptor instead.
func (*LoadTextOutput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{8}
}

func (x *LoadTextOutput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LoadTextOutput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LoadTextOutput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoadTextOutput) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *LoadTextOutput) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *LoadTextOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LoadPdfInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileContent     []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`             // PDF 文件二进制内容
	FileName        string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                      // 文件名（含扩展名）
	FilePath        string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                      // 原始文件路径（可选）
	TrackId         string                 `protobuf:"bytes,4,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`                         // 追踪 ID（可选）
	LoadingEngine   string                 `protobuf:"bytes,5,opt,name=loading_engine,json=loadingEngine,proto3" json:"loading_engine,omitempty"`       // 加载引擎："native"（pypdf）/ "docling"（默认 "native"）
	DecryptPassword string                 `protobuf:"bytes,6,opt,name=decrypt_password,json=decryptPassword,proto3" json:"decrypt_password,omitempty"` // PDF 解密密码（可选）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoadPdfInput) Reset() {
	*x = LoadPdfInput{}
	mi := &file_rag_insert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPdfInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPdfInput) ProtoMessage() {}

func (x *LoadPdfInput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPdfInput.ProtoReflect.Descriptor instead.
func (*LoadPdfInput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{9}
}

func (x *LoadPdfInput) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *LoadPdfInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LoadPdfInput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoadPdfInput) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *LoadPdfInput) GetLoadingEngine() string {
	if x != nil {
		return x.LoadingEngine
	}
	return ""
}

func (x *LoadPdfInput) GetDecryptPassword() string {
	if x != nil {
		return x.DecryptPassword
	}
	return ""
}

type LoadPdfOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                   // 提取的纯文本内容
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                 // 回显文件名
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                 // 回显文件路径
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`        // 内容 MD5 hash（用于去重）
	ContentLength int64                  `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // 提取文本长度
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`     // 错误信息（空字符串=成功）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPdfOutput) Reset() {
	*x = LoadPdfOutput{}
	mi := &file_rag_insert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPdfOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPdfOutput) ProtoMessage() {}

func (x *LoadPdfOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPdfOutput.ProtoReflect.Descriptor instead.
func (*LoadPdfOutput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{10}
}

func (x *LoadPdfOutput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LoadPdfOutput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LoadPdfOutput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoadPdfOutput) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *LoadPdfOutput) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *LoadPdfOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LoadDocxInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`       // DOCX 文件二进制内容
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                // 文件名（含扩展名）
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                // 原始文件路径（可选）
	TrackId       string                 `protobuf:"bytes,4,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`                   // 追踪 ID（可选）
	LoadingEngine string                 `protobuf:"bytes,5,opt,name=loading_engine,json=loadingEngine,proto3" json:"loading_engine,omitempty"` // 加载引擎："native"（python-docx）/ "docling"（默认 "native"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadDocxInput) Reset() {
	*x = LoadDocxInput{}
	mi := &file_rag_insert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadDocxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDocxInput) ProtoMessage() {}

func (x *LoadDocxInput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDocxInput.ProtoReflect.Descriptor instead.
func (*LoadDocxInput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{11}
}

func (x *LoadDocxInput) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *LoadDocxInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LoadDocxInput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoadDocxInput) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *LoadDocxInput) GetLoadingEngine() string {
	if x != nil {
		return x.LoadingEngine
	}
	return ""
}

type LoadDocxOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                   // 提取的纯文本内容
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`                 // 回显文件名
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                 // 回显文件路径
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`        // 内容 MD5 hash（用于去重）
	ContentLength int64                  `protobuf:"varint,5,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // 提取文本长度
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`     // 错误信息（空字符串=成功）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadDocxOutput) Reset() {
	*x = LoadDocxOutput{}
	mi := &file_rag_insert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadDocxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadDocxOutput) ProtoMessage() {}

func (x *LoadDocxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rag_insert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadDocxOutput.ProtoReflect.Descriptor instead.
func (*LoadDocxOutput) Descriptor() ([]byte, []int) {
	return file_rag_insert_proto_rawDescGZIP(), []int{12}
}

func (x *LoadDocxOutput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LoadDocxOutput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LoadDocxOutput) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LoadDocxOutput) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *LoadDocxOutput) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *LoadDocxOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_rag_insert_proto protoreflect.FileDescriptor

const file_rag_insert_proto_rawDesc = "" +
	"\n" +
	"\x10rag/insert.proto\x12\x1blightrag.eventbus.topics.v1\x1a\x13index/builder.proto\"\x8f\x02\n" +
	"\rChunkingInput\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1c\n" +
	"\ttokenizer\x18\x02 \x01(\fR\ttokenizer\x12(\n" +
	"\x10chunk_token_size\x18\x03 \x01(\x05R\x0echunkTokenSize\x127\n" +
	"\x18chunk_overlap_token_size\x18\x04 \x01(\x05R\x15chunkOverlapTokenSize\x12,\n" +
	"\x12split_by_character\x18\x05 \x01(\tR\x10splitByCharacter\x125\n" +
	"\x17split_by_character_only\x18\x06 \x01(\bR\x14splitByCharacterOnly\"P\n" +
	"\x0eChunkingOutput\x12>\n" +
	"\x06chunks\x18\x01 \x03(\v2&.lightrag.eventbus.topics.v1.ChunkItemR\x06chunks\"i\n" +
	"\tChunkItem\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\x12*\n" +
	"\x11chunk_order_index\x18\x03 \x01(\x05R\x0fchunkOrderIndex\"&\n" +
	"\x0eEmbeddingInput\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"_\n" +
	"\x0fEmbeddingOutput\x12L\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2,.lightrag.eventbus.topics.v1.EmbeddingVectorR\n" +
	"embeddings\"<\n" +
	"\bOcrInput\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"\x1f\n" +
	"\tOcrOutput\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x87\x01\n" +
	"\rLoadTextInput\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x19\n" +
	"\btrack_id\x18\x04 \x01(\tR\atrackId\"\xd3\x01\n" +
	"\x0eLoadTextOutput\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xd8\x01\n" +
	"\fLoadPdfInput\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x19\n" +
	"\btrack_id\x18\x04 \x01(\tR\atrackId\x12%\n" +
	"\x0eloading_engine\x18\x05 \x01(\tR\rloadingEngine\x12)\n" +
	"\x10decrypt_password\x18\x06 \x01(\tR\x0fdecryptPassword\"\xd2\x01\n" +
	"\rLoadPdfOutput\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xae\x01\n" +
	"\rLoadDocxInput\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x19\n" +
	"\btrack_id\x18\x04 \x01(\tR\atrackId\x12%\n" +
	"\x0eloading_engine\x18\x05 \x01(\tR\rloadingEngine\"\xd3\x01\n" +
	"\x0eLoadDocxOutput\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12%\n" +
	"\x0econtent_length\x18\x05 \x01(\x03R\rcontentLength\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessageBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3"

var (
	file_rag_insert_proto_rawDescOnce sync.Once
	file_rag_insert_proto_rawDescData []byte
)

func file_rag_insert_proto_rawDescGZIP() []byte {
	file_rag_insert_proto_rawDescOnce.Do(func() {
		file_rag_insert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_insert_proto_rawDesc), len(file_rag_insert_proto_rawDesc)))
	})
	return file_rag_insert_proto_rawDescData
}

var file_rag_insert_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rag_insert_proto_goTypes = []any{
	(*ChunkingInput)(nil),   // 0: lightrag.eventbus.topics.v1.ChunkingInput
	(*ChunkingOutput)(nil),  // 1: lightrag.eventbus.topics.v1.ChunkingOutput
	(*ChunkItem)(nil),       // 2: lightrag.eventbus.topics.v1.ChunkItem
	(*EmbeddingInput)(nil),  // 3: lightrag.eventbus.topics.v1.EmbeddingInput
	(*EmbeddingOutput)(nil), // 4: lightrag.eventbus.topics.v1.EmbeddingOutput
	(*OcrInput)(nil),        // 5: lightrag.eventbus.topics.v1.OcrInput
	(*OcrOutput)(nil),       // 6: lightrag.eventbus.topics.v1.OcrOutput
	(*LoadTextInput)(nil),   // 7: lightrag.eventbus.topics.v1.LoadTextInput
	(*LoadTextOutput)(nil),  // 8: lightrag.eventbus.topics.v1.LoadTextOutput
	(*LoadPdfInput)(nil),    // 9: lightrag.eventbus.topics.v1.LoadPdfInput
	(*LoadPdfOutput)(nil),   // 10: lightrag.eventbus.topics.v1.LoadPdfOutput
	(*LoadDocxInput)(nil),   // 11: lightrag.eventbus.topics.v1.LoadDocxInput
	(*LoadDocxOutput)(nil),  // 12: lightrag.eventbus.topics.v1.LoadDocxOutput
	(*EmbeddingVector)(nil), // 13: lightrag.eventbus.topics.v1.EmbeddingVector
}
var file_rag_insert_proto_depIdxs = []int32{
	2,  // 0: lightrag.eventbus.topics.v1.ChunkingOutput.chunks:type_name -> lightrag.eventbus.topics.v1.ChunkItem
	13, // 1: lightrag.eventbus.topics.v1.EmbeddingOutput.embeddings:type_name -> lightrag.eventbus.topics.v1.EmbeddingVector
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rag_insert_proto_init() }
func file_rag_insert_proto_init() {
	if File_rag_insert_proto != nil {
		return
	}
	file_index_builder_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_insert_proto_rawDesc), len(file_rag_insert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rag_insert_proto_goTypes,
		DependencyIndexes: file_rag_insert_proto_depIdxs,
		MessageInfos:      file_rag_insert_proto_msgTypes,
	}.Build()
	File_rag_insert_proto = out.File
	file_rag_insert_proto_goTypes = nil
	file_rag_insert_proto_depIdxs = nil
}
