// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: insert.proto

package topics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkingInput struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Content               string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                                               // 原始文档内容
	Tokenizer             []byte                 `protobuf:"bytes,2,opt,name=tokenizer,proto3" json:"tokenizer,omitempty"`                                                           // 序列化的 Tiktoken tokenizer
	ChunkTokenSize        int32                  `protobuf:"varint,3,opt,name=chunk_token_size,json=chunkTokenSize,proto3" json:"chunk_token_size,omitempty"`                        // chunk token 大小 (默认 1200)
	ChunkOverlapTokenSize int32                  `protobuf:"varint,4,opt,name=chunk_overlap_token_size,json=chunkOverlapTokenSize,proto3" json:"chunk_overlap_token_size,omitempty"` // 重叠 token 数 (默认 100)
	SplitByCharacter      string                 `protobuf:"bytes,5,opt,name=split_by_character,json=splitByCharacter,proto3" json:"split_by_character,omitempty"`                   // 分隔符
	SplitByCharacterOnly  bool                   `protobuf:"varint,6,opt,name=split_by_character_only,json=splitByCharacterOnly,proto3" json:"split_by_character_only,omitempty"`    // 仅按字符分割 (默认 false)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChunkingInput) Reset() {
	*x = ChunkingInput{}
	mi := &file_insert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkingInput) ProtoMessage() {}

func (x *ChunkingInput) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkingInput.ProtoReflect.Descriptor instead.
func (*ChunkingInput) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkingInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkingInput) GetTokenizer() []byte {
	if x != nil {
		return x.Tokenizer
	}
	return nil
}

func (x *ChunkingInput) GetChunkTokenSize() int32 {
	if x != nil {
		return x.ChunkTokenSize
	}
	return 0
}

func (x *ChunkingInput) GetChunkOverlapTokenSize() int32 {
	if x != nil {
		return x.ChunkOverlapTokenSize
	}
	return 0
}

func (x *ChunkingInput) GetSplitByCharacter() string {
	if x != nil {
		return x.SplitByCharacter
	}
	return ""
}

func (x *ChunkingInput) GetSplitByCharacterOnly() bool {
	if x != nil {
		return x.SplitByCharacterOnly
	}
	return false
}

type ChunkingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ChunkItem           `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"` // 分块结果列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkingOutput) Reset() {
	*x = ChunkingOutput{}
	mi := &file_insert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkingOutput) ProtoMessage() {}

func (x *ChunkingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkingOutput.ProtoReflect.Descriptor instead.
func (*ChunkingOutput) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkingOutput) GetChunks() []*ChunkItem {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Content         string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                           // chunk 文本内容
	Tokens          int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`                                            // token 数量
	ChunkOrderIndex int32                  `protobuf:"varint,3,opt,name=chunk_order_index,json=chunkOrderIndex,proto3" json:"chunk_order_index,omitempty"` // chunk 在文档中的序号
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkItem) Reset() {
	*x = ChunkItem{}
	mi := &file_insert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkItem) ProtoMessage() {}

func (x *ChunkItem) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkItem.ProtoReflect.Descriptor instead.
func (*ChunkItem) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkItem) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *ChunkItem) GetChunkOrderIndex() int32 {
	if x != nil {
		return x.ChunkOrderIndex
	}
	return 0
}

type EmbeddingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`                                      // 待嵌入的文本列表
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`             // 嵌入模型名称
	EmbeddingDim  int32                  `protobuf:"varint,3,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`   // 嵌入维度
	MaxTokenSize  int32                  `protobuf:"varint,4,opt,name=max_token_size,json=maxTokenSize,proto3" json:"max_token_size,omitempty"` // 最大 token 数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingInput) Reset() {
	*x = EmbeddingInput{}
	mi := &file_insert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingInput) ProtoMessage() {}

func (x *EmbeddingInput) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingInput.ProtoReflect.Descriptor instead.
func (*EmbeddingInput) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{3}
}

func (x *EmbeddingInput) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *EmbeddingInput) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbeddingInput) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

func (x *EmbeddingInput) GetMaxTokenSize() int32 {
	if x != nil {
		return x.MaxTokenSize
	}
	return 0
}

type EmbeddingOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbeddingVector     `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"` // 嵌入结果列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingOutput) Reset() {
	*x = EmbeddingOutput{}
	mi := &file_insert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingOutput) ProtoMessage() {}

func (x *EmbeddingOutput) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingOutput.ProtoReflect.Descriptor instead.
func (*EmbeddingOutput) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingOutput) GetEmbeddings() []*EmbeddingVector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type EmbeddingVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // 向量值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingVector) Reset() {
	*x = EmbeddingVector{}
	mi := &file_insert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingVector) ProtoMessage() {}

func (x *EmbeddingVector) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingVector.ProtoReflect.Descriptor instead.
func (*EmbeddingVector) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{5}
}

func (x *EmbeddingVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type OcrInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`       // 图片二进制数据
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // OCR 语言 (默认 auto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrInput) Reset() {
	*x = OcrInput{}
	mi := &file_insert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrInput) ProtoMessage() {}

func (x *OcrInput) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrInput.ProtoReflect.Descriptor instead.
func (*OcrInput) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{6}
}

func (x *OcrInput) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *OcrInput) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type OcrOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // OCR 识别的文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrOutput) Reset() {
	*x = OcrOutput{}
	mi := &file_insert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrOutput) ProtoMessage() {}

func (x *OcrOutput) ProtoReflect() protoreflect.Message {
	mi := &file_insert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrOutput.ProtoReflect.Descriptor instead.
func (*OcrOutput) Descriptor() ([]byte, []int) {
	return file_insert_proto_rawDescGZIP(), []int{7}
}

func (x *OcrOutput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_insert_proto protoreflect.FileDescriptor

const file_insert_proto_rawDesc = "" +
	"\n" +
	"\finsert.proto\x12\x1blightrag.eventbus.topics.v1\"\x8f\x02\n" +
	"\rChunkingInput\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1c\n" +
	"\ttokenizer\x18\x02 \x01(\fR\ttokenizer\x12(\n" +
	"\x10chunk_token_size\x18\x03 \x01(\x05R\x0echunkTokenSize\x127\n" +
	"\x18chunk_overlap_token_size\x18\x04 \x01(\x05R\x15chunkOverlapTokenSize\x12,\n" +
	"\x12split_by_character\x18\x05 \x01(\tR\x10splitByCharacter\x125\n" +
	"\x17split_by_character_only\x18\x06 \x01(\bR\x14splitByCharacterOnly\"P\n" +
	"\x0eChunkingOutput\x12>\n" +
	"\x06chunks\x18\x01 \x03(\v2&.lightrag.eventbus.topics.v1.ChunkItemR\x06chunks\"i\n" +
	"\tChunkItem\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\x12*\n" +
	"\x11chunk_order_index\x18\x03 \x01(\x05R\x0fchunkOrderIndex\"\x90\x01\n" +
	"\x0eEmbeddingInput\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12#\n" +
	"\rembedding_dim\x18\x03 \x01(\x05R\fembeddingDim\x12$\n" +
	"\x0emax_token_size\x18\x04 \x01(\x05R\fmaxTokenSize\"_\n" +
	"\x0fEmbeddingOutput\x12L\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2,.lightrag.eventbus.topics.v1.EmbeddingVectorR\n" +
	"embeddings\")\n" +
	"\x0fEmbeddingVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"<\n" +
	"\bOcrInput\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"\x1f\n" +
	"\tOcrOutput\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3"

var (
	file_insert_proto_rawDescOnce sync.Once
	file_insert_proto_rawDescData []byte
)

func file_insert_proto_rawDescGZIP() []byte {
	file_insert_proto_rawDescOnce.Do(func() {
		file_insert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_insert_proto_rawDesc), len(file_insert_proto_rawDesc)))
	})
	return file_insert_proto_rawDescData
}

var file_insert_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_insert_proto_goTypes = []any{
	(*ChunkingInput)(nil),   // 0: lightrag.eventbus.topics.v1.ChunkingInput
	(*ChunkingOutput)(nil),  // 1: lightrag.eventbus.topics.v1.ChunkingOutput
	(*ChunkItem)(nil),       // 2: lightrag.eventbus.topics.v1.ChunkItem
	(*EmbeddingInput)(nil),  // 3: lightrag.eventbus.topics.v1.EmbeddingInput
	(*EmbeddingOutput)(nil), // 4: lightrag.eventbus.topics.v1.EmbeddingOutput
	(*EmbeddingVector)(nil), // 5: lightrag.eventbus.topics.v1.EmbeddingVector
	(*OcrInput)(nil),        // 6: lightrag.eventbus.topics.v1.OcrInput
	(*OcrOutput)(nil),       // 7: lightrag.eventbus.topics.v1.OcrOutput
}
var file_insert_proto_depIdxs = []int32{
	2, // 0: lightrag.eventbus.topics.v1.ChunkingOutput.chunks:type_name -> lightrag.eventbus.topics.v1.ChunkItem
	5, // 1: lightrag.eventbus.topics.v1.EmbeddingOutput.embeddings:type_name -> lightrag.eventbus.topics.v1.EmbeddingVector
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_insert_proto_init() }
func file_insert_proto_init() {
	if File_insert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_insert_proto_rawDesc), len(file_insert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_insert_proto_goTypes,
		DependencyIndexes: file_insert_proto_depIdxs,
		MessageInfos:      file_insert_proto_msgTypes,
	}.Build()
	File_insert_proto = out.File
	file_insert_proto_goTypes = nil
	file_insert_proto_depIdxs = nil
}
