// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: index/retriever.proto

package topics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrieveInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	IndexName string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"` // 目标索引名称，如 "thesaurus"
	Query     string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                          // 检索查询文本
	TopK      int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`               // 返回结果数量，默认 20
	// --- 召回策略控制 ---
	SemanticRatio float32   `protobuf:"fixed32,4,opt,name=semantic_ratio,json=semanticRatio,proto3" json:"semantic_ratio,omitempty"`  // 0=纯文本，1=纯语义；默认由服务配置决定
	QueryVector   []float32 `protobuf:"fixed32,5,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"` // 可选：预计算查询向量（不传则由 Retriever 内部调 Embedding）
	Embedder      string    `protobuf:"bytes,6,opt,name=embedder,proto3" json:"embedder,omitempty"`                                   // embedder 名称，默认 "default"
	// --- 过滤与截断 ---
	ScoreThreshold float32 `protobuf:"fixed32,7,opt,name=score_threshold,json=scoreThreshold,proto3" json:"score_threshold,omitempty"` // 最小相关性分数（如 0.65）
	FilterExpr     string  `protobuf:"bytes,8,opt,name=filter_expr,json=filterExpr,proto3" json:"filter_expr,omitempty"`               // 底层索引过滤表达式（如 Meilisearch filter 语法）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrieveInput) Reset() {
	*x = RetrieveInput{}
	mi := &file_index_retriever_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveInput) ProtoMessage() {}

func (x *RetrieveInput) ProtoReflect() protoreflect.Message {
	mi := &file_index_retriever_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveInput.ProtoReflect.Descriptor instead.
func (*RetrieveInput) Descriptor() ([]byte, []int) {
	return file_index_retriever_proto_rawDescGZIP(), []int{0}
}

func (x *RetrieveInput) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *RetrieveInput) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveInput) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveInput) GetSemanticRatio() float32 {
	if x != nil {
		return x.SemanticRatio
	}
	return 0
}

func (x *RetrieveInput) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *RetrieveInput) GetEmbedder() string {
	if x != nil {
		return x.Embedder
	}
	return ""
}

func (x *RetrieveInput) GetScoreThreshold() float32 {
	if x != nil {
		return x.ScoreThreshold
	}
	return 0
}

func (x *RetrieveInput) GetFilterExpr() string {
	if x != nil {
		return x.FilterExpr
	}
	return ""
}

type RetrieveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                                         // 原始文本或高亮文本（可选）
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 结构化字段（JSON 字符串或纯文本）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResult) Reset() {
	*x = RetrieveResult{}
	mi := &file_index_retriever_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResult) ProtoMessage() {}

func (x *RetrieveResult) ProtoReflect() protoreflect.Message {
	mi := &file_index_retriever_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResult.ProtoReflect.Descriptor instead.
func (*RetrieveResult) Descriptor() ([]byte, []int) {
	return file_index_retriever_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveResult) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RetrieveResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrieveResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrieveResult) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RetrieveOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RetrieveResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalHits     int32                  `protobuf:"varint,2,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"` // 命中总数（含被 threshold 过滤掉的）
	IndexName     string                 `protobuf:"bytes,3,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`  // 回显索引名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveOutput) Reset() {
	*x = RetrieveOutput{}
	mi := &file_index_retriever_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveOutput) ProtoMessage() {}

func (x *RetrieveOutput) ProtoReflect() protoreflect.Message {
	mi := &file_index_retriever_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveOutput.ProtoReflect.Descriptor instead.
func (*RetrieveOutput) Descriptor() ([]byte, []int) {
	return file_index_retriever_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveOutput) GetResults() []*RetrieveResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RetrieveOutput) GetTotalHits() int32 {
	if x != nil {
		return x.TotalHits
	}
	return 0
}

func (x *RetrieveOutput) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

var File_index_retriever_proto protoreflect.FileDescriptor

const file_index_retriever_proto_rawDesc = "" +
	"\n" +
	"\x15index/retriever.proto\x12\x1blightrag.eventbus.topics.v1\"\x8d\x02\n" +
	"\rRetrieveInput\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12%\n" +
	"\x0esemantic_ratio\x18\x04 \x01(\x02R\rsemanticRatio\x12%\n" +
	"\fquery_vector\x18\x05 \x03(\x02B\x02\x10\x01R\vqueryVector\x12\x1a\n" +
	"\bembedder\x18\x06 \x01(\tR\bembedder\x12'\n" +
	"\x0fscore_threshold\x18\a \x01(\x02R\x0escoreThreshold\x12\x1f\n" +
	"\vfilter_expr\x18\b \x01(\tR\n" +
	"filterExpr\"\xed\x01\n" +
	"\x0eRetrieveResult\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12O\n" +
	"\x06fields\x18\x04 \x03(\v27.lightrag.eventbus.topics.v1.RetrieveResult.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x0eRetrieveOutput\x12E\n" +
	"\aresults\x18\x01 \x03(\v2+.lightrag.eventbus.topics.v1.RetrieveResultR\aresults\x12\x1d\n" +
	"\n" +
	"total_hits\x18\x02 \x01(\x05R\ttotalHits\x12\x1d\n" +
	"\n" +
	"index_name\x18\x03 \x01(\tR\tindexNameBDZBgithub.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go/topics;topicsb\x06proto3"

var (
	file_index_retriever_proto_rawDescOnce sync.Once
	file_index_retriever_proto_rawDescData []byte
)

func file_index_retriever_proto_rawDescGZIP() []byte {
	file_index_retriever_proto_rawDescOnce.Do(func() {
		file_index_retriever_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_index_retriever_proto_rawDesc), len(file_index_retriever_proto_rawDesc)))
	})
	return file_index_retriever_proto_rawDescData
}

var file_index_retriever_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_index_retriever_proto_goTypes = []any{
	(*RetrieveInput)(nil),  // 0: lightrag.eventbus.topics.v1.RetrieveInput
	(*RetrieveResult)(nil), // 1: lightrag.eventbus.topics.v1.RetrieveResult
	(*RetrieveOutput)(nil), // 2: lightrag.eventbus.topics.v1.RetrieveOutput
	nil,                    // 3: lightrag.eventbus.topics.v1.RetrieveResult.FieldsEntry
}
var file_index_retriever_proto_depIdxs = []int32{
	3, // 0: lightrag.eventbus.topics.v1.RetrieveResult.fields:type_name -> lightrag.eventbus.topics.v1.RetrieveResult.FieldsEntry
	1, // 1: lightrag.eventbus.topics.v1.RetrieveOutput.results:type_name -> lightrag.eventbus.topics.v1.RetrieveResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_index_retriever_proto_init() }
func file_index_retriever_proto_init() {
	if File_index_retriever_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_index_retriever_proto_rawDesc), len(file_index_retriever_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_index_retriever_proto_goTypes,
		DependencyIndexes: file_index_retriever_proto_depIdxs,
		MessageInfos:      file_index_retriever_proto_msgTypes,
	}.Build()
	File_index_retriever_proto = out.File
	file_index_retriever_proto_goTypes = nil
	file_index_retriever_proto_depIdxs = nil
}
