// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v6.33.6
// source: index/retriever.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lightrag.eventbus.topics.v1";

export interface RetrieveInput {
  /** 目标索引名称，如 "thesaurus" */
  indexName: string;
  /** 检索查询文本 */
  query: string;
  /** 返回结果数量，默认 20 */
  topK: number;
  /** --- 召回策略控制 --- */
  semanticRatio: number;
  /** 可选：预计算查询向量（不传则由 Retriever 内部调 Embedding） */
  queryVector: number[];
  /** embedder 名称，默认 "default" */
  embedder: string;
  /** --- 过滤与截断 --- */
  scoreThreshold: number;
  /** 底层索引过滤表达式（如 Meilisearch filter 语法） */
  filterExpr: string;
}

export interface RetrieveResult {
  documentId: string;
  score: number;
  /** 原始文本或高亮文本（可选） */
  content: string;
  /** 结构化字段（JSON 字符串或纯文本） */
  fields: { [key: string]: string };
}

export interface RetrieveResult_FieldsEntry {
  key: string;
  value: string;
}

export interface RetrieveOutput {
  results: RetrieveResult[];
  /** 命中总数（含被 threshold 过滤掉的） */
  totalHits: number;
  /** 回显索引名 */
  indexName: string;
}

function createBaseRetrieveInput(): RetrieveInput {
  return {
    indexName: "",
    query: "",
    topK: 0,
    semanticRatio: 0,
    queryVector: [],
    embedder: "",
    scoreThreshold: 0,
    filterExpr: "",
  };
}

export const RetrieveInput: MessageFns<RetrieveInput> = {
  encode(message: RetrieveInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.indexName !== "") {
      writer.uint32(10).string(message.indexName);
    }
    if (message.query !== "") {
      writer.uint32(18).string(message.query);
    }
    if (message.topK !== 0) {
      writer.uint32(24).int32(message.topK);
    }
    if (message.semanticRatio !== 0) {
      writer.uint32(37).float(message.semanticRatio);
    }
    writer.uint32(42).fork();
    for (const v of message.queryVector) {
      writer.float(v);
    }
    writer.join();
    if (message.embedder !== "") {
      writer.uint32(50).string(message.embedder);
    }
    if (message.scoreThreshold !== 0) {
      writer.uint32(61).float(message.scoreThreshold);
    }
    if (message.filterExpr !== "") {
      writer.uint32(66).string(message.filterExpr);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetrieveInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetrieveInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.indexName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.topK = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.semanticRatio = reader.float();
          continue;
        }
        case 5: {
          if (tag === 45) {
            message.queryVector.push(reader.float());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.queryVector.push(reader.float());
            }

            continue;
          }

          break;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.embedder = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.scoreThreshold = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.filterExpr = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RetrieveInput>, I>>(base?: I): RetrieveInput {
    return RetrieveInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetrieveInput>, I>>(object: I): RetrieveInput {
    const message = createBaseRetrieveInput();
    message.indexName = object.indexName ?? "";
    message.query = object.query ?? "";
    message.topK = object.topK ?? 0;
    message.semanticRatio = object.semanticRatio ?? 0;
    message.queryVector = object.queryVector?.map((e) => e) || [];
    message.embedder = object.embedder ?? "";
    message.scoreThreshold = object.scoreThreshold ?? 0;
    message.filterExpr = object.filterExpr ?? "";
    return message;
  },
};

function createBaseRetrieveResult(): RetrieveResult {
  return { documentId: "", score: 0, content: "", fields: {} };
}

export const RetrieveResult: MessageFns<RetrieveResult> = {
  encode(message: RetrieveResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.documentId !== "") {
      writer.uint32(10).string(message.documentId);
    }
    if (message.score !== 0) {
      writer.uint32(21).float(message.score);
    }
    if (message.content !== "") {
      writer.uint32(26).string(message.content);
    }
    globalThis.Object.entries(message.fields).forEach(([key, value]: [string, string]) => {
      RetrieveResult_FieldsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetrieveResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetrieveResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.documentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.score = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = RetrieveResult_FieldsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.fields[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RetrieveResult>, I>>(base?: I): RetrieveResult {
    return RetrieveResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetrieveResult>, I>>(object: I): RetrieveResult {
    const message = createBaseRetrieveResult();
    message.documentId = object.documentId ?? "";
    message.score = object.score ?? 0;
    message.content = object.content ?? "";
    message.fields = (globalThis.Object.entries(object.fields ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseRetrieveResult_FieldsEntry(): RetrieveResult_FieldsEntry {
  return { key: "", value: "" };
}

export const RetrieveResult_FieldsEntry: MessageFns<RetrieveResult_FieldsEntry> = {
  encode(message: RetrieveResult_FieldsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetrieveResult_FieldsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetrieveResult_FieldsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RetrieveResult_FieldsEntry>, I>>(base?: I): RetrieveResult_FieldsEntry {
    return RetrieveResult_FieldsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetrieveResult_FieldsEntry>, I>>(object: I): RetrieveResult_FieldsEntry {
    const message = createBaseRetrieveResult_FieldsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseRetrieveOutput(): RetrieveOutput {
  return { results: [], totalHits: 0, indexName: "" };
}

export const RetrieveOutput: MessageFns<RetrieveOutput> = {
  encode(message: RetrieveOutput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      RetrieveResult.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.totalHits !== 0) {
      writer.uint32(16).int32(message.totalHits);
    }
    if (message.indexName !== "") {
      writer.uint32(26).string(message.indexName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RetrieveOutput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRetrieveOutput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.results.push(RetrieveResult.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalHits = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.indexName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RetrieveOutput>, I>>(base?: I): RetrieveOutput {
    return RetrieveOutput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RetrieveOutput>, I>>(object: I): RetrieveOutput {
    const message = createBaseRetrieveOutput();
    message.results = object.results?.map((e) => RetrieveResult.fromPartial(e)) || [];
    message.totalHits = object.totalHits ?? 0;
    message.indexName = object.indexName ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
