// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: lightrag_eventbus.proto

package eventbus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 合并策略：订阅者主动决定
type SubscriberReply_MergeStrategy int32

const (
	SubscriberReply_APPEND  SubscriberReply_MergeStrategy = 0 // 追加 (适合扩词、抽取实体)
	SubscriberReply_REPLACE SubscriberReply_MergeStrategy = 1 // 替换/覆盖 (适合更高优的算法，如专有分块算法覆盖默认算法)
	SubscriberReply_IGNORE  SubscriberReply_MergeStrategy = 2 // 旁路/忽略 (适合审计、敏感词拦截)
)

// Enum value maps for SubscriberReply_MergeStrategy.
var (
	SubscriberReply_MergeStrategy_name = map[int32]string{
		0: "APPEND",
		1: "REPLACE",
		2: "IGNORE",
	}
	SubscriberReply_MergeStrategy_value = map[string]int32{
		"APPEND":  0,
		"REPLACE": 1,
		"IGNORE":  2,
	}
)

func (x SubscriberReply_MergeStrategy) Enum() *SubscriberReply_MergeStrategy {
	p := new(SubscriberReply_MergeStrategy)
	*p = x
	return p
}

func (x SubscriberReply_MergeStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriberReply_MergeStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_lightrag_eventbus_proto_enumTypes[0].Descriptor()
}

func (SubscriberReply_MergeStrategy) Type() protoreflect.EnumType {
	return &file_lightrag_eventbus_proto_enumTypes[0]
}

func (x SubscriberReply_MergeStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriberReply_MergeStrategy.Descriptor instead.
func (SubscriberReply_MergeStrategy) EnumDescriptor() ([]byte, []int) {
	return file_lightrag_eventbus_proto_rawDescGZIP(), []int{3, 0}
}

// 健康状态与熔断建议
type SubscriberReply_HealthStatus int32

const (
	SubscriberReply_HEALTHY    SubscriberReply_HealthStatus = 0
	SubscriberReply_DEGRADED   SubscriberReply_HealthStatus = 1 // 服务可用但性能下降
	SubscriberReply_OVERLOADED SubscriberReply_HealthStatus = 2 // 负载过高，建议熔断
	SubscriberReply_UNHEALTHY  SubscriberReply_HealthStatus = 3 // 服务不可用
)

// Enum value maps for SubscriberReply_HealthStatus.
var (
	SubscriberReply_HealthStatus_name = map[int32]string{
		0: "HEALTHY",
		1: "DEGRADED",
		2: "OVERLOADED",
		3: "UNHEALTHY",
	}
	SubscriberReply_HealthStatus_value = map[string]int32{
		"HEALTHY":    0,
		"DEGRADED":   1,
		"OVERLOADED": 2,
		"UNHEALTHY":  3,
	}
)

func (x SubscriberReply_HealthStatus) Enum() *SubscriberReply_HealthStatus {
	p := new(SubscriberReply_HealthStatus)
	*p = x
	return p
}

func (x SubscriberReply_HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriberReply_HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lightrag_eventbus_proto_enumTypes[1].Descriptor()
}

func (SubscriberReply_HealthStatus) Type() protoreflect.EnumType {
	return &file_lightrag_eventbus_proto_enumTypes[1]
}

func (x SubscriberReply_HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriberReply_HealthStatus.Descriptor instead.
func (SubscriberReply_HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_lightrag_eventbus_proto_rawDescGZIP(), []int{3, 1}
}

type SubscriberReply_AdvisoryAction int32

const (
	SubscriberReply_CONTINUE      SubscriberReply_AdvisoryAction = 0 // 正常继续
	SubscriberReply_CIRCUIT_BREAK SubscriberReply_AdvisoryAction = 1 // 建议熔断此订阅者 (如 30s 内不派发新任务)
	SubscriberReply_RETRY         SubscriberReply_AdvisoryAction = 2 // 建议总线重试分发
	SubscriberReply_FALLBACK      SubscriberReply_AdvisoryAction = 3 // 建议总线降级到默认实现
)

// Enum value maps for SubscriberReply_AdvisoryAction.
var (
	SubscriberReply_AdvisoryAction_name = map[int32]string{
		0: "CONTINUE",
		1: "CIRCUIT_BREAK",
		2: "RETRY",
		3: "FALLBACK",
	}
	SubscriberReply_AdvisoryAction_value = map[string]int32{
		"CONTINUE":      0,
		"CIRCUIT_BREAK": 1,
		"RETRY":         2,
		"FALLBACK":      3,
	}
)

func (x SubscriberReply_AdvisoryAction) Enum() *SubscriberReply_AdvisoryAction {
	p := new(SubscriberReply_AdvisoryAction)
	*p = x
	return p
}

func (x SubscriberReply_AdvisoryAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriberReply_AdvisoryAction) Descriptor() protoreflect.EnumDescriptor {
	return file_lightrag_eventbus_proto_enumTypes[2].Descriptor()
}

func (SubscriberReply_AdvisoryAction) Type() protoreflect.EnumType {
	return &file_lightrag_eventbus_proto_enumTypes[2]
}

func (x SubscriberReply_AdvisoryAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriberReply_AdvisoryAction.Descriptor instead.
func (SubscriberReply_AdvisoryAction) EnumDescriptor() ([]byte, []int) {
	return file_lightrag_eventbus_proto_rawDescGZIP(), []int{3, 2}
}

type RegisterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId      string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`                   // 订阅者唯一ID (如: "rust-semantic-chunker-node1")
	Topic             string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`                                                     // 订阅的阶段 (如: "rag.insert.chunking")
	Capabilities      []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                       // 细粒度能力声明 (如: ["markdown", "pdf"])
	MaxConcurrency    int32                  `protobuf:"varint,4,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`            // 声明最大并发处理能力 (用于背压)
	ExpectedLatencyMs int32                  `protobuf:"varint,5,opt,name=expected_latency_ms,json=expectedLatencyMs,proto3" json:"expected_latency_ms,omitempty"` // 预期处理延迟 (用于总线调度参考)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_lightrag_eventbus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lightrag_eventbus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_lightrag_eventbus_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *RegisterRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *RegisterRequest) GetExpectedLatencyMs() int32 {
	if x != nil {
		return x.ExpectedLatencyMs
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_lightrag_eventbus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lightrag_eventbus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_lightrag_eventbus_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EventEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                                                                                  // 路由 Topic (如: "rag.insert.chunking")
	CorrelationId     string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`                                             // 全局唯一的请求标识 (匹配 Request/Reply)
	TraceId           string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                                               // OpenTelemetry 追踪 ID
	DeadlineTimestamp int64                  `protobuf:"varint,4,opt,name=deadline_timestamp,json=deadlineTimestamp,proto3" json:"deadline_timestamp,omitempty"`                                // 绝对截止时间戳 (Unix Epoch毫秒)，用于精确超时控制
	Priority          int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                                                           // 优先级 (0: Normal, 1: High)
	SourceService     string                 `protobuf:"bytes,6,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`                                             // 发起者标识 (如: "lightrag-core-api")
	Inputs            map[string][]byte      `protobuf:"bytes,10,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // 业务上下文负载 (如果是瘦事件，这里可能只有 "document_id")
	Metadata          map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 附加元数据
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_lightrag_eventbus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_lightrag_eventbus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_lightrag_eventbus_proto_rawDescGZIP(), []int{2}
}

func (x *EventEnvelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventEnvelope) GetDeadlineTimestamp() int64 {
	if x != nil {
		return x.DeadlineTimestamp
	}
	return 0
}

func (x *EventEnvelope) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EventEnvelope) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *EventEnvelope) GetInputs() map[string][]byte {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *EventEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SubscriberReply struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	CorrelationId string                        `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`                                           // 必须与请求中的 correlation_id 对应
	SubscriberId  string                        `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`                                              // 回包者标识
	Outputs       map[string][]byte             `protobuf:"bytes,10,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 处理后的增量结果
	Strategy      SubscriberReply_MergeStrategy `protobuf:"varint,11,opt,name=strategy,proto3,enum=lightrag.eventbus.v1.SubscriberReply_MergeStrategy" json:"strategy,omitempty"`
	Weight        int32                         `protobuf:"varint,12,opt,name=weight,proto3" json:"weight,omitempty"`                                    // 冲突解决权重 (权重大的 REPLACE 覆盖小的)
	PartialResult bool                          `protobuf:"varint,13,opt,name=partial_result,json=partialResult,proto3" json:"partial_result,omitempty"` // 流式标识: 是否只是部分结果 (支持渐进式返回)
	// 运维与可观测性
	LatencyMs     int32                          `protobuf:"varint,20,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                                                       // 订阅者内部处理耗时
	ErrorCode     string                         `protobuf:"bytes,21,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                                                        // 标准错误码 (成功为空，如 RATE_LIMIT)
	ErrorMessage  string                         `protobuf:"bytes,22,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                               // 错误详情
	Metadata      map[string][]byte              `protobuf:"bytes,23,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 订阅者回传元数据 (如 Token 消耗)
	Health        SubscriberReply_HealthStatus   `protobuf:"varint,24,opt,name=health,proto3,enum=lightrag.eventbus.v1.SubscriberReply_HealthStatus" json:"health,omitempty"`
	Advisory      SubscriberReply_AdvisoryAction `protobuf:"varint,25,opt,name=advisory,proto3,enum=lightrag.eventbus.v1.SubscriberReply_AdvisoryAction" json:"advisory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriberReply) Reset() {
	*x = SubscriberReply{}
	mi := &file_lightrag_eventbus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberReply) ProtoMessage() {}

func (x *SubscriberReply) ProtoReflect() protoreflect.Message {
	mi := &file_lightrag_eventbus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberReply.ProtoReflect.Descriptor instead.
func (*SubscriberReply) Descriptor() ([]byte, []int) {
	return file_lightrag_eventbus_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriberReply) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *SubscriberReply) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscriberReply) GetOutputs() map[string][]byte {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *SubscriberReply) GetStrategy() SubscriberReply_MergeStrategy {
	if x != nil {
		return x.Strategy
	}
	return SubscriberReply_APPEND
}

func (x *SubscriberReply) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SubscriberReply) GetPartialResult() bool {
	if x != nil {
		return x.PartialResult
	}
	return false
}

func (x *SubscriberReply) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *SubscriberReply) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SubscriberReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SubscriberReply) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SubscriberReply) GetHealth() SubscriberReply_HealthStatus {
	if x != nil {
		return x.Health
	}
	return SubscriberReply_HEALTHY
}

func (x *SubscriberReply) GetAdvisory() SubscriberReply_AdvisoryAction {
	if x != nil {
		return x.Advisory
	}
	return SubscriberReply_CONTINUE
}

var File_lightrag_eventbus_proto protoreflect.FileDescriptor

const file_lightrag_eventbus_proto_rawDesc = "" +
	"\n" +
	"\x17lightrag_eventbus.proto\x12\x14lightrag.eventbus.v1\"\xc9\x01\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12'\n" +
	"\x0fmax_concurrency\x18\x04 \x01(\x05R\x0emaxConcurrency\x12.\n" +
	"\x13expected_latency_ms\x18\x05 \x01(\x05R\x11expectedLatencyMs\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe9\x03\n" +
	"\rEventEnvelope\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12-\n" +
	"\x12deadline_timestamp\x18\x04 \x01(\x03R\x11deadlineTimestamp\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12%\n" +
	"\x0esource_service\x18\x06 \x01(\tR\rsourceService\x12G\n" +
	"\x06inputs\x18\n" +
	" \x03(\v2/.lightrag.eventbus.v1.EventEnvelope.InputsEntryR\x06inputs\x12M\n" +
	"\bmetadata\x18\v \x03(\v21.lightrag.eventbus.v1.EventEnvelope.MetadataEntryR\bmetadata\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\a\n" +
	"\x0fSubscriberReply\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\x12L\n" +
	"\aoutputs\x18\n" +
	" \x03(\v22.lightrag.eventbus.v1.SubscriberReply.OutputsEntryR\aoutputs\x12O\n" +
	"\bstrategy\x18\v \x01(\x0e23.lightrag.eventbus.v1.SubscriberReply.MergeStrategyR\bstrategy\x12\x16\n" +
	"\x06weight\x18\f \x01(\x05R\x06weight\x12%\n" +
	"\x0epartial_result\x18\r \x01(\bR\rpartialResult\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x14 \x01(\x05R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"error_code\x18\x15 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x16 \x01(\tR\ferrorMessage\x12O\n" +
	"\bmetadata\x18\x17 \x03(\v23.lightrag.eventbus.v1.SubscriberReply.MetadataEntryR\bmetadata\x12J\n" +
	"\x06health\x18\x18 \x01(\x0e22.lightrag.eventbus.v1.SubscriberReply.HealthStatusR\x06health\x12P\n" +
	"\badvisory\x18\x19 \x01(\x0e24.lightrag.eventbus.v1.SubscriberReply.AdvisoryActionR\badvisory\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"4\n" +
	"\rMergeStrategy\x12\n" +
	"\n" +
	"\x06APPEND\x10\x00\x12\v\n" +
	"\aREPLACE\x10\x01\x12\n" +
	"\n" +
	"\x06IGNORE\x10\x02\"H\n" +
	"\fHealthStatus\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\f\n" +
	"\bDEGRADED\x10\x01\x12\x0e\n" +
	"\n" +
	"OVERLOADED\x10\x02\x12\r\n" +
	"\tUNHEALTHY\x10\x03\"J\n" +
	"\x0eAdvisoryAction\x12\f\n" +
	"\bCONTINUE\x10\x00\x12\x11\n" +
	"\rCIRCUIT_BREAK\x10\x01\x12\t\n" +
	"\x05RETRY\x10\x02\x12\f\n" +
	"\bFALLBACK\x10\x032\x82\x03\n" +
	"\bEventBus\x12c\n" +
	"\x12RegisterSubscriber\x12%.lightrag.eventbus.v1.RegisterRequest\x1a&.lightrag.eventbus.v1.RegisterResponse\x12Y\n" +
	"\tSubscribe\x12%.lightrag.eventbus.v1.RegisterRequest\x1a#.lightrag.eventbus.v1.EventEnvelope0\x01\x12X\n" +
	"\aRespond\x12%.lightrag.eventbus.v1.SubscriberReply\x1a&.lightrag.eventbus.v1.RegisterResponse\x12\\\n" +
	"\x0ePublishAndWait\x12#.lightrag.eventbus.v1.EventEnvelope\x1a%.lightrag.eventbus.v1.SubscriberReplyB[\n" +
	"\x18com.lightrag.eventbus.v1P\x01Z=github.com/juncaifeng/LightRAG/go-eventbus/sdk/v1/go;eventbusb\x06proto3"

var (
	file_lightrag_eventbus_proto_rawDescOnce sync.Once
	file_lightrag_eventbus_proto_rawDescData []byte
)

func file_lightrag_eventbus_proto_rawDescGZIP() []byte {
	file_lightrag_eventbus_proto_rawDescOnce.Do(func() {
		file_lightrag_eventbus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lightrag_eventbus_proto_rawDesc), len(file_lightrag_eventbus_proto_rawDesc)))
	})
	return file_lightrag_eventbus_proto_rawDescData
}

var file_lightrag_eventbus_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lightrag_eventbus_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lightrag_eventbus_proto_goTypes = []any{
	(SubscriberReply_MergeStrategy)(0),  // 0: lightrag.eventbus.v1.SubscriberReply.MergeStrategy
	(SubscriberReply_HealthStatus)(0),   // 1: lightrag.eventbus.v1.SubscriberReply.HealthStatus
	(SubscriberReply_AdvisoryAction)(0), // 2: lightrag.eventbus.v1.SubscriberReply.AdvisoryAction
	(*RegisterRequest)(nil),             // 3: lightrag.eventbus.v1.RegisterRequest
	(*RegisterResponse)(nil),            // 4: lightrag.eventbus.v1.RegisterResponse
	(*EventEnvelope)(nil),               // 5: lightrag.eventbus.v1.EventEnvelope
	(*SubscriberReply)(nil),             // 6: lightrag.eventbus.v1.SubscriberReply
	nil,                                 // 7: lightrag.eventbus.v1.EventEnvelope.InputsEntry
	nil,                                 // 8: lightrag.eventbus.v1.EventEnvelope.MetadataEntry
	nil,                                 // 9: lightrag.eventbus.v1.SubscriberReply.OutputsEntry
	nil,                                 // 10: lightrag.eventbus.v1.SubscriberReply.MetadataEntry
}
var file_lightrag_eventbus_proto_depIdxs = []int32{
	7,  // 0: lightrag.eventbus.v1.EventEnvelope.inputs:type_name -> lightrag.eventbus.v1.EventEnvelope.InputsEntry
	8,  // 1: lightrag.eventbus.v1.EventEnvelope.metadata:type_name -> lightrag.eventbus.v1.EventEnvelope.MetadataEntry
	9,  // 2: lightrag.eventbus.v1.SubscriberReply.outputs:type_name -> lightrag.eventbus.v1.SubscriberReply.OutputsEntry
	0,  // 3: lightrag.eventbus.v1.SubscriberReply.strategy:type_name -> lightrag.eventbus.v1.SubscriberReply.MergeStrategy
	10, // 4: lightrag.eventbus.v1.SubscriberReply.metadata:type_name -> lightrag.eventbus.v1.SubscriberReply.MetadataEntry
	1,  // 5: lightrag.eventbus.v1.SubscriberReply.health:type_name -> lightrag.eventbus.v1.SubscriberReply.HealthStatus
	2,  // 6: lightrag.eventbus.v1.SubscriberReply.advisory:type_name -> lightrag.eventbus.v1.SubscriberReply.AdvisoryAction
	3,  // 7: lightrag.eventbus.v1.EventBus.RegisterSubscriber:input_type -> lightrag.eventbus.v1.RegisterRequest
	3,  // 8: lightrag.eventbus.v1.EventBus.Subscribe:input_type -> lightrag.eventbus.v1.RegisterRequest
	6,  // 9: lightrag.eventbus.v1.EventBus.Respond:input_type -> lightrag.eventbus.v1.SubscriberReply
	5,  // 10: lightrag.eventbus.v1.EventBus.PublishAndWait:input_type -> lightrag.eventbus.v1.EventEnvelope
	4,  // 11: lightrag.eventbus.v1.EventBus.RegisterSubscriber:output_type -> lightrag.eventbus.v1.RegisterResponse
	5,  // 12: lightrag.eventbus.v1.EventBus.Subscribe:output_type -> lightrag.eventbus.v1.EventEnvelope
	4,  // 13: lightrag.eventbus.v1.EventBus.Respond:output_type -> lightrag.eventbus.v1.RegisterResponse
	6,  // 14: lightrag.eventbus.v1.EventBus.PublishAndWait:output_type -> lightrag.eventbus.v1.SubscriberReply
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_lightrag_eventbus_proto_init() }
func file_lightrag_eventbus_proto_init() {
	if File_lightrag_eventbus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lightrag_eventbus_proto_rawDesc), len(file_lightrag_eventbus_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lightrag_eventbus_proto_goTypes,
		DependencyIndexes: file_lightrag_eventbus_proto_depIdxs,
		EnumInfos:         file_lightrag_eventbus_proto_enumTypes,
		MessageInfos:      file_lightrag_eventbus_proto_msgTypes,
	}.Build()
	File_lightrag_eventbus_proto = out.File
	file_lightrag_eventbus_proto_goTypes = nil
	file_lightrag_eventbus_proto_depIdxs = nil
}
