// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: lightrag_eventbus.proto

package eventbus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventBus_RegisterSubscriber_FullMethodName   = "/lightrag.eventbus.v1.EventBus/RegisterSubscriber"
	EventBus_Subscribe_FullMethodName            = "/lightrag.eventbus.v1.EventBus/Subscribe"
	EventBus_Respond_FullMethodName              = "/lightrag.eventbus.v1.EventBus/Respond"
	EventBus_PublishAndWait_FullMethodName       = "/lightrag.eventbus.v1.EventBus/PublishAndWait"
	EventBus_RegisterService_FullMethodName      = "/lightrag.eventbus.v1.EventBus/RegisterService"
	EventBus_Heartbeat_FullMethodName            = "/lightrag.eventbus.v1.EventBus/Heartbeat"
	EventBus_UnregisterService_FullMethodName    = "/lightrag.eventbus.v1.EventBus/UnregisterService"
	EventBus_ListServiceInstances_FullMethodName = "/lightrag.eventbus.v1.EventBus/ListServiceInstances"
)

// EventBusClient is the client API for EventBus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventBusClient interface {
	// 【控制平面】订阅者启动时注册
	RegisterSubscriber(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 【数据平面】数据分发：订阅者只接收事件流 (单向流)
	// 稳定性更高，负载均衡更友好。订阅者需通过独立的 Respond RPC 传回结果。
	Subscribe(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error)
	// 【数据平面】数据回传：订阅者处理完毕后通过独立的 RPC 返回结果
	Respond(ctx context.Context, in *SubscriberReply, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 【数据平面】主服务(LightRAG)调用接口：发布事件并等待总线聚合结果
	PublishAndWait(ctx context.Context, in *EventEnvelope, opts ...grpc.CallOption) (*SubscriberReply, error)
	// 【控制平面】服务实例注册
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	// 【控制平面】服务心跳续期
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 【控制平面】服务实例注销
	UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 【控制平面】查询服务实例列表
	ListServiceInstances(ctx context.Context, in *ListServiceInstancesRequest, opts ...grpc.CallOption) (*ListServiceInstancesResponse, error)
}

type eventBusClient struct {
	cc grpc.ClientConnInterface
}

func NewEventBusClient(cc grpc.ClientConnInterface) EventBusClient {
	return &eventBusClient{cc}
}

func (c *eventBusClient) RegisterSubscriber(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, EventBus_RegisterSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventBusClient) Subscribe(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventBus_ServiceDesc.Streams[0], EventBus_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterRequest, EventEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventBus_SubscribeClient = grpc.ServerStreamingClient[EventEnvelope]

func (c *eventBusClient) Respond(ctx context.Context, in *SubscriberReply, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, EventBus_Respond_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventBusClient) PublishAndWait(ctx context.Context, in *EventEnvelope, opts ...grpc.CallOption) (*SubscriberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriberReply)
	err := c.cc.Invoke(ctx, EventBus_PublishAndWait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventBusClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, EventBus_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventBusClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, EventBus_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventBusClient) UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, EventBus_UnregisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventBusClient) ListServiceInstances(ctx context.Context, in *ListServiceInstancesRequest, opts ...grpc.CallOption) (*ListServiceInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceInstancesResponse)
	err := c.cc.Invoke(ctx, EventBus_ListServiceInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventBusServer is the server API for EventBus service.
// All implementations must embed UnimplementedEventBusServer
// for forward compatibility.
type EventBusServer interface {
	// 【控制平面】订阅者启动时注册
	RegisterSubscriber(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 【数据平面】数据分发：订阅者只接收事件流 (单向流)
	// 稳定性更高，负载均衡更友好。订阅者需通过独立的 Respond RPC 传回结果。
	Subscribe(*RegisterRequest, grpc.ServerStreamingServer[EventEnvelope]) error
	// 【数据平面】数据回传：订阅者处理完毕后通过独立的 RPC 返回结果
	Respond(context.Context, *SubscriberReply) (*RegisterResponse, error)
	// 【数据平面】主服务(LightRAG)调用接口：发布事件并等待总线聚合结果
	PublishAndWait(context.Context, *EventEnvelope) (*SubscriberReply, error)
	// 【控制平面】服务实例注册
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	// 【控制平面】服务心跳续期
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 【控制平面】服务实例注销
	UnregisterService(context.Context, *UnregisterServiceRequest) (*RegisterResponse, error)
	// 【控制平面】查询服务实例列表
	ListServiceInstances(context.Context, *ListServiceInstancesRequest) (*ListServiceInstancesResponse, error)
	mustEmbedUnimplementedEventBusServer()
}

// UnimplementedEventBusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventBusServer struct{}

func (UnimplementedEventBusServer) RegisterSubscriber(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSubscriber not implemented")
}
func (UnimplementedEventBusServer) Subscribe(*RegisterRequest, grpc.ServerStreamingServer[EventEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEventBusServer) Respond(context.Context, *SubscriberReply) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Respond not implemented")
}
func (UnimplementedEventBusServer) PublishAndWait(context.Context, *EventEnvelope) (*SubscriberReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishAndWait not implemented")
}
func (UnimplementedEventBusServer) RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedEventBusServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEventBusServer) UnregisterService(context.Context, *UnregisterServiceRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterService not implemented")
}
func (UnimplementedEventBusServer) ListServiceInstances(context.Context, *ListServiceInstancesRequest) (*ListServiceInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceInstances not implemented")
}
func (UnimplementedEventBusServer) mustEmbedUnimplementedEventBusServer() {}
func (UnimplementedEventBusServer) testEmbeddedByValue()                  {}

// UnsafeEventBusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventBusServer will
// result in compilation errors.
type UnsafeEventBusServer interface {
	mustEmbedUnimplementedEventBusServer()
}

func RegisterEventBusServer(s grpc.ServiceRegistrar, srv EventBusServer) {
	// If the following call panics, it indicates UnimplementedEventBusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventBus_ServiceDesc, srv)
}

func _EventBus_RegisterSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBusServer).RegisterSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBus_RegisterSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBusServer).RegisterSubscriber(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventBus_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventBusServer).Subscribe(m, &grpc.GenericServerStream[RegisterRequest, EventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventBus_SubscribeServer = grpc.ServerStreamingServer[EventEnvelope]

func _EventBus_Respond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriberReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBusServer).Respond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBus_Respond_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBusServer).Respond(ctx, req.(*SubscriberReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventBus_PublishAndWait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBusServer).PublishAndWait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBus_PublishAndWait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBusServer).PublishAndWait(ctx, req.(*EventEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventBus_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBusServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBus_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBusServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventBus_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBusServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBus_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBusServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventBus_UnregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBusServer).UnregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBus_UnregisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBusServer).UnregisterService(ctx, req.(*UnregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventBus_ListServiceInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventBusServer).ListServiceInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventBus_ListServiceInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventBusServer).ListServiceInstances(ctx, req.(*ListServiceInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventBus_ServiceDesc is the grpc.ServiceDesc for EventBus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventBus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightrag.eventbus.v1.EventBus",
	HandlerType: (*EventBusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSubscriber",
			Handler:    _EventBus_RegisterSubscriber_Handler,
		},
		{
			MethodName: "Respond",
			Handler:    _EventBus_Respond_Handler,
		},
		{
			MethodName: "PublishAndWait",
			Handler:    _EventBus_PublishAndWait_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _EventBus_RegisterService_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _EventBus_Heartbeat_Handler,
		},
		{
			MethodName: "UnregisterService",
			Handler:    _EventBus_UnregisterService_Handler,
		},
		{
			MethodName: "ListServiceInstances",
			Handler:    _EventBus_ListServiceInstances_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _EventBus_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lightrag_eventbus.proto",
}
