# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import session_pb2 as session__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionServiceStub(object):
    """=============================================================================
    gRPC Service 定义
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/services.session.v1.SessionService/CreateSession',
                request_serializer=session__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=session__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/services.session.v1.SessionService/GetSession',
                request_serializer=session__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=session__pb2.Session.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/services.session.v1.SessionService/UpdateSession',
                request_serializer=session__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=session__pb2.Session.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/services.session.v1.SessionService/DeleteSession',
                request_serializer=session__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=session__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/services.session.v1.SessionService/ListSessions',
                request_serializer=session__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=session__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.AppendMessage = channel.unary_unary(
                '/services.session.v1.SessionService/AppendMessage',
                request_serializer=session__pb2.AppendMessageRequest.SerializeToString,
                response_deserializer=session__pb2.AppendMessageResponse.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/services.session.v1.SessionService/ListMessages',
                request_serializer=session__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=session__pb2.ListMessagesResponse.FromString,
                _registered_method=True)


class SessionServiceServicer(object):
    """=============================================================================
    gRPC Service 定义
    =============================================================================

    """

    def CreateSession(self, request, context):
        """会话 CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendMessage(self, request, context):
        """消息历史
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=session__pb2.CreateSessionRequest.FromString,
                    response_serializer=session__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=session__pb2.GetSessionRequest.FromString,
                    response_serializer=session__pb2.Session.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=session__pb2.UpdateSessionRequest.FromString,
                    response_serializer=session__pb2.Session.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=session__pb2.DeleteSessionRequest.FromString,
                    response_serializer=session__pb2.DeleteResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=session__pb2.ListSessionsRequest.FromString,
                    response_serializer=session__pb2.ListSessionsResponse.SerializeToString,
            ),
            'AppendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendMessage,
                    request_deserializer=session__pb2.AppendMessageRequest.FromString,
                    response_serializer=session__pb2.AppendMessageResponse.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=session__pb2.ListMessagesRequest.FromString,
                    response_serializer=session__pb2.ListMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.session.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.session.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """=============================================================================
    gRPC Service 定义
    =============================================================================

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.session.v1.SessionService/CreateSession',
            session__pb2.CreateSessionRequest.SerializeToString,
            session__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.session.v1.SessionService/GetSession',
            session__pb2.GetSessionRequest.SerializeToString,
            session__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.session.v1.SessionService/UpdateSession',
            session__pb2.UpdateSessionRequest.SerializeToString,
            session__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.session.v1.SessionService/DeleteSession',
            session__pb2.DeleteSessionRequest.SerializeToString,
            session__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.session.v1.SessionService/ListSessions',
            session__pb2.ListSessionsRequest.SerializeToString,
            session__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.session.v1.SessionService/AppendMessage',
            session__pb2.AppendMessageRequest.SerializeToString,
            session__pb2.AppendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.session.v1.SessionService/ListMessages',
            session__pb2.ListMessagesRequest.SerializeToString,
            session__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
